import type { LearningUnit } from './types';

const checkedAt = '2026-10-05';

const sources = {
  languageModels: {
    title: 'Google：语言模型入门',
    url: 'https://developers.google.com/machine-learning/crash-course/llm',
    checkedAt,
    scope: '页面更新于 2026-01-09。支持语言模型按上下文估计内容概率、生成语言及 Token 的基础解释；不作为具体模型能力或选型结论。',
  },
  tokens: {
    title: 'Google：理解与计算 Token',
    url: 'https://ai.google.dev/gemini-api/docs/tokens',
    checkedAt,
    scope: '官方文档支持 Token、输入输出计量和上下文限制的解释。本文不引用具体模型容量、当前价格或字符换算比例；核对日期不是首次发布日期。',
  },
  tuning: {
    title: 'Google：微调与提示词工程',
    url: 'https://developers.google.com/machine-learning/crash-course/llm/tuning',
    checkedAt,
    scope: '页面更新于 2025-12-03。支持提示词不改变模型参数、微调通过任务样本继续训练的区别；不证明微调必然提高效果或能够替代检索。',
  },
  vectorSearch: {
    title: 'Microsoft：向量检索的原理与使用方式',
    url: 'https://learn.microsoft.com/en-us/azure/search/vector-search-overview',
    checkedAt,
    scope: '页面更新于 2026-08-05。支持嵌入表示、向量相似度检索及结合关键词的方式；相似度不证明资料有效或足以支持结论。',
  },
  functionCalling: {
    title: 'Google：函数调用的工作方式',
    url: 'https://ai.google.dev/gemini-api/docs/function-calling',
    checkedAt,
    scope: '页面更新于 2026-09-23。支持模型提出函数名称和参数、应用执行工具的职责区分，以及执行前检查建议。保存核对是本课的流程建议，不以示例代码证明企业部署安全。',
  },
  rag: {
    title: 'Lewis 等：检索增强生成原论文',
    url: 'https://arxiv.org/abs/2005.11401',
    checkedAt,
    scope: '2020-05-22 首次提交，2021-04-12 修订。支持外部检索与生成结合的原理；公开任务实验不证明企业问答效果。',
  },
  permissions: {
    title: 'Microsoft：Azure AI Search 文档级权限',
    url: 'https://learn.microsoft.com/en-us/azure/search/search-document-level-access-overview',
    checkedAt,
    scope: '页面更新于 2026-09-17。支持按身份过滤资料及权限元数据同步条件；部分原生集成仍为预览，不能视为所有连接器的统一保证。',
  },
  answers: {
    title: 'Microsoft：生成回答的能力与限制',
    url: 'https://learn.microsoft.com/en-us/microsoft-copilot-studio/faqs-generative-answers',
    checkedAt,
    scope: '页面更新于 2026-05-30。说明回答可能出错、来源未被自动检查准确性；不能推导引用、模型一致或流畅表达等于事实核验。',
  },
  handoff: {
    title: 'Microsoft：转接人工的条件',
    url: 'https://learn.microsoft.com/en-us/microsoft-copilot-studio/advanced-hand-off',
    checkedAt,
    scope: '页面更新于 2026-08-03。支持客服平台连接、上下文传递和转接触发条件；不证明人工已接单或问题已解决。',
  },
  agents: {
    title: 'Anthropic：Building effective agents',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    checkedAt,
    scope: '2024-12-19 发布。采用其工作流与 Agent 的架构区分、检查点和停止条件；页面已提示工具生态发生变化，本文不沿用旧工具推荐或推断行业普遍收益。',
  },
  mcp: {
    title: 'MCP：宿主、客户端与服务端的职责',
    url: 'https://modelcontextprotocol.io/specification/2025-06-18/architecture',
    checkedAt,
    scope: '固定查看 2025-06-18 版架构说明，支持连接结构、能力协商及宿主的授权责任。此版本用于讲原理，不宣称是最新协议，也不证明接入即安全。',
  },
  evaluations: {
    title: '阿里云百炼：模型评测',
    url: 'https://help.aliyun.com/zh/model-studio/model-evaluation-overview',
    checkedAt,
    scope: '本次核对到自定义与基线评测，以及模型、规则和人工三类评分方式。页面未取得可确认的更新日期；功能、地域及价格应在使用前另查，示例阈值不是通用合格线。',
  },
  risk: {
    title: 'NIST AI RMF 1.0：风险管理的核心活动',
    url: 'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/',
    checkedAt,
    scope: '2023 年框架摘录；页面提示修订进行中。支持情境、责任、测量和持续风险管理的关系。它是自愿框架，本课的访谈、成本与交接方法为编辑设计，不是认证清单。',
  },
  gleanRole: {
    title: 'Glean：AI Success Manager, Central 岗位原页',
    url: 'https://job-boards.greenhouse.io/gleanwork/jobs/4661884005',
    checkedAt,
    scope: '2026-10-05 可读取的岗位样本，未取得首次发布日期。职责涉及发现、部署、采用和价值测量，面试含 AI 练习或讨论；仅代表该岗位当时的要求，不代表招聘趋势或录用保证。',
  },
} as const satisfies Record<string, LearningUnit['sources'][number]>;

/** Review content only. These units do not approve publication or migrate legacy progress. */
export const learningDraftUnits: readonly LearningUnit[] = [
  {
    id: 'LU-001',
    slug: 'ai-foundations',
    title: '先理解模型怎样回答，再比较它能做什么',
    summary: '模型可以整理和生成语言，但流畅不等于正确。把任务、可用材料与验收标准分开，才能理解模型选择。',
    minutes: 6,
    group: 'principles',
    concepts: [
      { term: '大语言模型（LLM）', meaning: '根据输入内容生成语言的模型。它的输出需要结合任务和证据判断，不能直接当成已核实事实。' },
      { term: 'Token 与上下文', meaning: 'Token 是模型处理内容的单位，不固定等于一个字。上下文是本轮可用的指令、资料等信息，其容量有限。' },
      { term: '提示词（Prompt）', meaning: '提供给模型的任务指令、问题或示例。修改提示词改变输入，本身不改变模型参数。' },
      { term: '嵌入表示（Embedding）', meaning: '把内容转换成一组数字，称为向量，便于比较内容的相似程度。' },
      { term: '向量检索（Vector Search）', meaning: '按向量的接近程度找候选资料，可与关键词检索结合。相似不等于正确或适用。' },
      { term: '微调（Fine-tuning）', meaning: '用任务样本继续训练，调整模型参数。给对话上传一份文件本身不是微调。' },
    ],
    explanation: [
      'Google 的教材解释，语言模型依据上下文估计后续内容的可能性，再生成语言。把任务写清楚有助于限定问题，但流畅回答仍可能出错。容量说明能处理多少材料，不能证明材料真实。',
      '检索增强生成（RAG）是在回答时先找相关资料，再交给模型组织答案。向量检索可用于找资料，但仍需检查权限、版本和适用条件。检索到一份相似文件，不等于它能回答当前问题。',
      '区分三种改变：提示词改输入；RAG 在回答时补充检索资料；微调用样本继续训练、改变模型参数。检索这个步骤本身不是训练。它们可以结合，是否需要微调要通过任务验证。',
      '本课建议用相同任务和材料比较模型，检查遗漏、错误、等待和人工修改。名称、价格与容量应记录日期；摘要与权益判断要有不同验收标准。一次好结果不能证明所有任务都适用。',
    ],
    example: {
      scene: '虚构示例：通用企业的客户经理准备设备续约会谈，行业背景待补。',
      input: '提供公开产品说明和虚构会议记录，要求区分“待确认问题”与“已有事实”。',
      ai: '整理会前简报草稿，分清客户已表达的需求与待验证判断。',
      human: '核对事实，删去无依据的预算、意向或采购时间推断。',
      next: '简报经审核后用于讨论，假设转为访谈问题。',
      conditions: '材料须可用且相关。未提供的信息仍是未知，完整回答不能证明已做外部调查。',
    },
    judgments: [
      '回答更长、语气更肯定或术语更多，都不是质量证据。先看是否准确完成约定任务。',
      '演示比较可以揭示问题，但不能据此承诺某模型在所有客户任务上最好。',
    ],
    steps: [
      { title: '先说清问题', detail: '能用自己的话解释：本次要模型整理什么，哪些结论必须另找依据。' },
      { title: '可选的小比较', detail: '用同一份公开材料比较两份回答，找出一项遗漏、一项无依据判断；无需购买服务或上传客户资料。' },
    ],
    takeaway: '先比较任务完成的证据，再比较模型名称。',
    quiz: {
      question: '模型能接收更长文件，并且写出很完整的客户简报，是否足以证明它更适合你的销售团队？',
      answer: '还不够。要核对资料使用、事实与假设的区分、遗漏和人工修改，还要看等待与实际用量。容量只说明能处理多少，适用性要由团队的任务验证。',
    },
    sources: [sources.languageModels, sources.tokens, sources.tuning, sources.vectorSearch, sources.rag, sources.answers],
    topicSlugs: ['agent-business-model', 'ai-poc-scale'],
    toolIds: ['company-role-research'],
    relatedItemIds: ['ST-005', 'ST-009'],
    legacySections: ['literacy'],
  },
  {
    id: 'LU-002',
    slug: 'knowledge-answers',
    title: '知识库回答：找到依据，还要确认权限与适用条件',
    summary: '沿着一个虚构售后问题，看身份、资料版本和审批责任怎样改变回答。完整图解和条件实验在本课展开。',
    minutes: 8,
    group: 'principles',
    concepts: [
      { term: '检索增强生成（RAG）', meaning: '先找相关资料，再让模型结合问题和资料组织回答。' },
      { term: '文档权限', meaning: '决定某个身份可以读取哪些资料的规则；提示词不能代替授权检查。' },
    ],
    explanation: [
      'RAG 原论文把外部检索与生成结合。企业使用这种思路时，还需配置资料范围、权限、更新和回答规则。上传文件不等于完成知识治理。',
      '完整示范分别讲清检索原理、虚构售后场景、可能业务价值和实际部署条件。交互结果来自明确规则，没有调用模型，也没有连接客户系统。',
    ],
    example: {
      scene: '虚构示例：客户经理询问客户甲的故障设备能否免费换新。行业背景待补。',
      input: '问题、设备信息，以及当前身份获准使用的规程和条款。',
      ai: '整理可用依据，说明缺口，形成受条件约束的回答。',
      human: '售后核实故障，合同负责人确认权益，有权人员作出审批。',
      next: '回答进入处理单；请求转接、人工接手和最终解决分别记录。',
      conditions: '资料适用且有效，权限同步完成，存在真实接管流程；缺少任一项就明确停在哪里。',
    },
    judgments: ['有引用不等于已核实；未查到不等于不存在；能解释规则不等于有权批准。'],
    steps: [{ title: '跟随条件实验', detail: '每次重置后只改变一个条件，观察依据、回答和接管状态如何变化。' }],
    takeaway: '能找到依据、能解释规则、能批准办理，是三种不同能力。',
    quiz: { question: '回答引用了规程，又显示已请求转人工，能否向客户承诺免费换新？', answer: '不能。还需核对适用条件、审批权与人工接单证据，转接请求本身不代表批准或解决。' },
    sources: [sources.rag, sources.permissions, sources.answers, sources.handoff],
    topicSlugs: ['ai-trust-governance', 'ai-poc-scale'],
    toolIds: ['poc-success-canvas'],
    relatedItemIds: ['ST-005', 'ST-006', 'ST-009'],
    legacySections: ['literacy', 'questions'],
  },
  {
    id: 'LU-003',
    slug: 'workflow-agents',
    title: '从生成文字到执行动作，中间需要哪些控制',
    summary: '用会前准备与纪要草稿解释工作流、Agent 和工具连接。关注谁决定下一步，以及失败后如何停止。',
    minutes: 7,
    group: 'principles',
    concepts: [
      { term: '工作流（Workflow）', meaning: '按事先定义的步骤安排模型和工具，例如先读材料，再生成提纲，最后人工检查。' },
      { term: '智能体（Agent）', meaning: '本课采用模型根据任务和工具结果动态选择后续步骤的定义；行业用法并不完全统一。' },
      { term: '函数调用（Function Calling）', meaning: '模型按约定格式提出工具调用请求，再由应用检查和执行。请求格式正确不等于获得操作权限。' },
      { term: '模型上下文协议（MCP）', meaning: '让 AI 应用与工具或资料服务交换信息的一种协议，连接能力与操作授权需要分别处理。' },
    ],
    explanation: [
      '聊天回答主要产生内容；工具调用还可能查询系统、建立记录或改变业务状态。应用收到函数调用请求后，需要检查是否允许执行、执行哪个对象。工具返回成功与业务结果已核实，也要分别确认。',
      'Anthropic 的工程文章区分预定路径的工作流和由模型动态选择步骤的 Agent，并建议只在任务需要时增加复杂度。这是其架构划分与工程建议，不能理解成所有系统的统一命名，也不能推导 Agent 一定优于固定流程。',
      'MCP 架构把应用宿主、连接客户端和能力服务分开，并把授权等职责交给宿主。可以把它理解为共同的连接方式，而不是业务审批制度。接上一个系统，不代表模型可以读取所有客户或执行所有动作。',
      '本课建议从一次只读、可检查的流程理解执行边界：每一步说明输入、结果、允许动作和失败出口。结果未知时先查询状态；不能因为没有看到成功提示，就反复提交同一笔业务操作。',
    ],
    example: {
      scene: '虚构示例：客户经理希望把会前公开资料研究和会后纪要整理连起来。行业背景待补。',
      input: '公开产品页、人工提供的虚构议程，以及允许使用的工具清单。',
      ai: '查找资料、整理访谈问题，再把会议摘要草稿交给客户经理核对。',
      human: '确认事实、参会角色和行动责任；涉及发消息或更新客户系统时另行批准。',
      next: '本课停在经核对的草稿。真实写入还需要对象确认、权限检查、保存结果及必要回读。',
      conditions: '工具范围清楚，失败可发现，有停止条件。资料或工具返回的文字不能改变用户授权。',
    },
    judgments: [
      '步骤固定而且容易检查时，可以先用简单工作流；动态选择带来的价值需要实测。',
      '会调用工具不等于能稳定完成流程，连接器数量也不能证明生产适用性。',
    ],
    steps: [
      { title: '分开内容与动作', detail: '指出示例中哪一步只生成文字，哪一步一旦执行就会影响他人或业务记录。' },
      { title: '可选流程练习', detail: '画出三步流程，在一个步骤旁写明允许范围、失败后的停止点与负责人。' },
    ],
    takeaway: '先说清允许它做什么，再讨论它能自主做多少。',
    quiz: { question: '模型按正确格式生成了更新客户记录的参数，系统是否可以直接执行？', answer: '不应仅凭格式执行。还要确认用户授权、目标对象和字段，检查权限与业务条件，并能确认保存结果。模型提出调用请求与应用批准执行是不同环节。' },
    sources: [sources.agents, sources.mcp, sources.functionCalling],
    topicSlugs: ['agent-business-model', 'ai-trust-governance'],
    toolIds: ['poc-success-canvas'],
    relatedItemIds: ['ST-004', 'ST-028'],
    legacySections: ['literacy', 'questions'],
  },
  {
    id: 'LU-004',
    slug: 'customer-discovery',
    title: '客户说想用 AI，先找出工作卡在哪里',
    summary: '从角色、输入、判断和交接理解需求。把技术愿望转成可验证的问题，才能决定是否值得进入方案讨论。',
    minutes: 7,
    group: 'customer',
    concepts: [
      { term: '需求发现', meaning: '与客户核对当前工作、问题影响、限制和决定方式，而非把一句需求直接翻译成功能清单。' },
      { term: '基线', meaning: '改变之前的比较起点，需说明观察对象、期间、计算方法和数据来源。' },
      { term: '价值假设', meaning: '对某项改变可能带来何种结果的暂时判断，必须保留成立条件和验证方式。' },
    ],
    explanation: [
      '“做一个知识库”可能对应查找困难、规则冲突，也可能是找不到审批人。它们需要的交付不同。发现阶段先还原一项工作如何开始、经过谁、在哪里等待、怎样结束，才能知道模型是否作用在真正的问题上。',
      'NIST 风险管理框架强调使用情境、目标、参与者和限制。Glean 的一个岗位样本也要求理解客户工作流，并把用例转成带负责人和成功标准的计划。这些来源支持关注情境与责任；下面的访谈顺序是本课的编辑方法。',
      '可以先问最近一次具体经历，再问出现频率和后果。区分当事人观察、系统记录与销售推测。如果尚无基线，就写明需要谁提供什么信息。未知不等于零，也不能被供应商案例中的改善比例填上。',
      '最后确认谁使用、谁维护资料、谁能接受风险、谁决定预算，以及下一步会据什么证据继续或停止。销售不必独自回答技术与安全问题，但要让问题有负责人，避免所有人都赞成试一试却没人承担后续工作。',
    ],
    example: {
      scene: '虚构示例：一家企业的售后主管希望引入“智能助手”。行业背景待补。',
      input: '用虚构工单重现一次服务过程，记录查询资料、判断权益、审批和回复四个环节。',
      ai: '整理访谈线索与待验证问题，不能把受访者的猜测自动改成经营事实。',
      human: '一线人员说明工作，资料负责人解释规则，主管核实问题优先级和可投入资源。',
      next: '如果主要卡在查找，讨论检索试验；若卡在审批，先讨论责任与流程，不急于扩大模型能力。',
      conditions: '客户愿意核对现状，问题有明确边界；没有真实资料时，本课只练习提问，不推断客户痛点。',
    },
    judgments: [
      '用户、受益者、预算负责人可能是不同角色，不能把使用意愿直接当成采购承诺。',
      '下一步应换来新的客户证据或决定；重复演示本身不能证明机会在推进。',
    ],
    steps: [
      { title: '先复述流程', detail: '不用产品名称，说明谁在什么环节遇到什么问题，以及后果由谁承担。' },
      { title: '可选访谈准备', detail: '从发现访谈工具中选择三个问题；真实客户信息留在获准使用的工作环境中。' },
    ],
    takeaway: '先查明工作怎样受阻，再决定 AI 应改变哪一步。',
    quiz: { question: '业务负责人说“员工找资料很慢”，是否已经足以写下节省工时的销售承诺？', answer: '还没有。要核对哪些员工、什么资料、耗时如何记录，以及等待究竟来自查找、判断还是审批。先形成有条件的假设，再决定试验和验收方式。' },
    sources: [sources.risk, sources.gleanRole],
    topicSlugs: ['ai-buying-committee', 'workflow-adoption'],
    toolIds: ['discovery-interview', 'ai-maturity-scan'],
    relatedItemIds: ['ST-011', 'ST-013', 'ST-016'],
    legacySections: ['definition', 'profile', 'questions'],
  },
  {
    id: 'LU-005',
    slug: 'value-and-cost',
    title: '把价值算清楚：节省时间并不自动变成利润',
    summary: '分开改善假设、真实采用和全部投入。理解客户怎样付费，也要理解完成一项任务究竟花了什么。',
    minutes: 7,
    group: 'customer',
    concepts: [
      { term: '总拥有成本（TCO）', meaning: '在明确期间和范围内，为取得并持续使用方案支付的产品、集成、运行、复核及管理等投入。' },
      { term: '单位任务成本', meaning: '完成一项定义清楚的业务任务所需的总投入；应包括失败、重试和人工恢复。' },
      { term: '采用', meaning: '目标人员在实际工作中使用方案；有账号、参加培训或打开页面都不足以证明任务已经改变。' },
    ],
    explanation: [
      '客户购买的可能是席位、用量或项目服务，而内部关心的是任务结果。计费单位与价值单位不同：一次请求便宜，不代表解决一个工单便宜；生成草稿很快，也可能把时间转移到复核与纠错。',
      'Google 的 Token 文档说明调用费用会受输入输出用量影响，但这不是完整业务成本。NIST 框架要求考虑预期益处、成本与使用范围。这两类事实提醒我们同时看技术消耗和业务后果，不能直接提供某客户的收益数字。',
      '本课建议先估计容量变化：适用任务量 × 真实采用比例 × 每项净省时间。净省时间应扣除新增复核和返工，三项数据使用同一期间和范围。这只是估算方法；没有测量时保留未知，不给一个看似精确的回报率。',
      '释放出的时间能否成为现金节约，还取决于是否减少外包、加班或其他支出，或者确实承接了新增工作。不要把同一份时间同时算成减员收益和增量收入。供应商报价、客户运营数据与财务认可的收益，需要分别说明出处。',
    ],
    example: {
      scene: '虚构示例：售后团队考虑用 AI 起草回复，行业背景待补。本例不设置假造的改善比例。',
      input: '需要核对适用工单量、原处理时间、AI 后复核和返工时间，以及产品与集成费用。',
      ai: '帮助整理计算口径与缺失项，依据已提供数据列情景；不能替未知值编造行业平均数。',
      human: '业务负责人确认任务量和采用，财务确认成本与收益口径，技术负责人说明运行投入。',
      next: '先形成可更新的价值假设。试验提供新证据后，再讨论范围、报价和是否继续。',
      conditions: '同类任务可比较，观察期间明确，质量未被牺牲；节省时间与兑现收益分别记录。',
    },
    judgments: [
      '效果案例可帮助提出问题；没有可比场景和测量方法，不能移植其百分比。',
      '价格、模型版本、用量条款和数据地域易变，应在具体采购时重查官方说明与合同。',
    ],
    steps: [
      { title: '辨认价值单位', detail: '说清你比较的是一次调用、一份合格草稿，还是一个最终解决的工单。' },
      { title: '可选口径练习', detail: '用价值假设工具列出已有数据和未知项；先解释公式，不急于填写收益。' },
    ],
    takeaway: '先证明任务改善，再判断改善怎样成为客户认可的价值。',
    quiz: { question: '回复草稿生成得更快了，但复核更久，能否直接用生成时间下降计算投资回报？', answer: '不能。应比较完整任务的净投入，并检查质量、采用和返工。即便确实释放时间，也需要说明如何兑现价值，再与方案的全部成本比较。' },
    sources: [sources.tokens, sources.risk],
    topicSlugs: ['agent-business-model', 'ai-poc-scale'],
    toolIds: ['value-hypothesis-one-pager'],
    relatedItemIds: ['ST-014', 'ST-017'],
    legacySections: ['literacy', 'questions'],
  },
  {
    id: 'LU-006',
    slug: 'pilot-evaluation',
    title: '试点要回答一个决定，而不只是得到一个分数',
    summary: '把演示、任务评测和生产条件分开。用正常与失败场景说明谁判定合格，以及试点后怎样作出决定。',
    minutes: 7,
    group: 'customer',
    concepts: [
      { term: '概念验证（POC）', meaning: '在约定范围内检验明确假设的试验，用结果支持继续、调整或停止的决定。' },
      { term: '评测（Evals）', meaning: '用一组任务、参考标准和判断方法检查系统表现，不是只挑几次成功演示。' },
      { term: '评分器（Grader）', meaning: '判断结果的规则、程序、模型或人工；它自己的判断方式也需要核对。' },
    ],
    explanation: [
      '一次演示说明系统在准备好的条件下做到了什么。评测要进一步询问：任务是否有代表性，怎样判断合格，失败发生在哪里。真实上线还要检查权限、资料更新、连接、接管和使用责任，因此一个平均分不能代替整个决策。',
      '阿里云百炼的文档区分自定义与基线评测，并提供模型、规则和人工评分。它证明这些评测路径存在，不能证明某个评分天然正确。客户任务涉及专业判断时，应由业务人员确认标准，并核对自动评分与人工判断的差异。',
      '本课建议在试验前约定问题、范围、参考答案或判定规则、参与者和结束时要做的决定。样本要覆盖常见任务，也要包含无答案、冲突、越权和工具失败。涉及高损失错误时，单列不能接受的情况，别让平均分把它们掩盖。',
      '试验结束时分别报告任务质量、完整流程投入和生产缺口。没有预算或运营责任，不等于试验没有价值，但需要明确下一步仍缺什么。开始一轮新测试，应有尚待回答的问题，而不是为了延长一个没有决定的试点。',
    ],
    example: {
      scene: '虚构示例：企业试验售后知识问答，行业背景待补，暂不允许自动向客户作出权益承诺。',
      input: '使用获准资料和虚构问题，包含现行条款、旧版规则、资料缺失与不同查询身份。',
      ai: '产生回答、引用或拒答；系统记录资料、版本、时间和失败状态，供评测使用。',
      human: '业务专家先定义可接受结果，再核对回答；安全人员检查越权情形，运营人员验证接管。',
      next: '根据预先约定的证据决定缩小范围、修正后再试，或进入另行批准的上线准备。',
      conditions: '评测样本与使用范围相符，评分可复查，模型或资料变化后检查受影响任务。',
    },
    judgments: [
      '模型给自己打高分，不等于业务正确。多个模型一致，也不能替代原始依据。',
      '试点合格只覆盖已验证的任务和环境，不能直接推广为所有用户、资料与场景均合格。',
    ],
    steps: [
      { title: '先确定结束时的决定', detail: '一句话说明试验要帮助谁决定什么，以及什么结果会让团队停止。' },
      { title: '可选失败案例练习', detail: '在成功标准画布中加入一个“应拒答”案例和一个“需要人工接管”案例，写出理由。' },
    ],
    takeaway: '好的试点让决定更有依据，失败结果也能提供价值。',
    quiz: { question: '问答平均得分很高，但曾把其他客户的条款展示出来，是否可以用总体表现解释为合格？', answer: '不可以。越权应作为独立问题处理，先查原因、修复并验证。平均分只汇总指定指标，不能消除不可接受的错误或替代上线批准。' },
    sources: [sources.evaluations, sources.permissions],
    topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    toolIds: ['poc-success-canvas'],
    relatedItemIds: ['ST-005', 'ST-009', 'ST-012'],
    legacySections: ['literacy', 'questions'],
  },
  {
    id: 'LU-007',
    slug: 'adoption-and-governance',
    title: '上线以后，谁维护知识、处理例外并决定暂停',
    summary: '部署、持续使用和业务结果是不同状态。把责任、权限更新和人工接管放进工作流程，才能讨论持续运营。',
    minutes: 7,
    group: 'practice',
    concepts: [
      { term: '生产环境', meaning: '面向真实使用者、资料和业务责任持续运行的环境，与教学演示或隔离测试不同。' },
      { term: '治理', meaning: '明确谁能决定、谁执行、如何发现问题和处理例外，并在变化后持续复核。' },
      { term: '人工接管', meaning: '人员收到必要上下文并明确接手后续处理；仅出现转接提示还不能证明接管完成。' },
    ],
    explanation: [
      '系统上线只说明可供使用。团队是否愿意用、能否正确复核、遇到例外是否有人负责，需要另外观察。若原本的流程仍要求重复录入，或者员工不清楚何时能信任回答，新增工具可能只增加一道操作。这里是流程分析，不是已测得的收益结论。',
      'NIST 框架把责任、监测和持续风险管理放在系统生命周期中。可以据此问：谁维护资料，谁调整权限，谁接收反馈，谁有权暂停。框架是自愿参考；填写一张表不等于风险已经受控，更不等于取得合规认证。',
      'Azure 的文档说明权限变化需要同步到索引；Copilot Studio 的转接文档说明真实接管需要客服平台集成。这些条件提醒我们，源系统改了权限和页面显示转接，都是流程中的一个环节，仍要验证后续结果。',
      '本课建议先选明确范围运行，观察任务完成、返工和例外，保留反馈入口及暂停方式。模型、资料、组织分工变化时，检查相关影响。扩展应依据可持续运行的证据，而不是只依据账号数、培训人数或一段成功演示。',
    ],
    example: {
      scene: '虚构示例：售后团队准备使用知识助手，行业背景待补，先限定到一种公开规程问答。',
      input: '现行资料、角色清单、更新责任、使用边界与人工服务时间。',
      ai: '整理资料并提示缺口；系统把异常交给指定渠道，保留必要的处理状态。',
      human: '资料负责人审核更新，技术人员验证连接与权限，主管安排接单并决定是否暂停使用。',
      next: '接单人继续核实；确认解决后结束处理。重复问题进入资料或流程改进，不自动改写规则。',
      conditions: '转接无人接单时显示等待及后续渠道。日志也可能包含敏感资料，应按获准范围保存和访问。',
    },
    judgments: [
      '接管、批准和解决分别需要证据。不要把转接请求数量直接当成解决数量。',
      '数据是否用于训练、保存多久、在哪处理，要按具体产品、设置和合同核对，不能用一句“企业级安全”替代。',
    ],
    steps: [
      { title: '找到四类责任', detail: '能指出示例中谁维护资料、谁维护系统、谁处理业务例外、谁决定暂停。' },
      { title: '可选交接练习', detail: '只用虚构问题说明交给谁、带哪些依据、缺什么，以及无人接单时停在哪里。' },
    ],
    takeaway: '持续运行依靠明确责任和可核对的状态，功能上线只是其中一步。',
    quiz: { question: '旧员工的资料权限已在源系统撤销，是否可以立即认定所有 AI 查询都已禁止访问？', answer: '不能直接认定。需要核对所用连接与索引的同步机制，并验证实际查询结果。源权限变化是起点，不能代替下游生效的证据。' },
    sources: [sources.risk, sources.permissions, sources.handoff],
    topicSlugs: ['workflow-adoption', 'ai-trust-governance'],
    toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'],
    relatedItemIds: ['ST-006', 'ST-026', 'ST-027'],
    legacySections: ['profile', 'literacy', 'questions'],
  },
  {
    id: 'LU-008',
    slug: 'career-evidence',
    title: '把已有销售经验，整理成可追问的 AI 岗位证据',
    summary: '岗位名称会变，结果责任和证据仍要说清。用真实经历、明确练习和当前岗位原页判断能力差距。',
    minutes: 7,
    group: 'practice',
    concepts: [
      { term: '岗位描述（JD）', meaning: '企业对某个具体岗位的职责和要求说明，是研究样本，不是整个行业的统一能力标准。' },
      { term: '能力证据', meaning: '能说明自己承担什么、如何判断和行动、产生什么结果以及如何核对的材料。' },
      { term: 'AI 流利度', meaning: '本课用来指能解释、使用并校验 AI 的工作能力；只会列工具名称不足以展示这种能力。' },
    ],
    explanation: [
      '复杂销售中的发现、协作、谈判和复盘，可以继续成为转岗证据。新增问题是：能否解释模型边界，理解数据与权限，定义试验结果，并与技术和运营人员交接。是否需要亲自开发，应看目标岗位，不能假定每个销售都要成为工程师。',
      '本次核对的 Glean AI Success Manager 岗位，把发现、部署、采用和价值测量放在职责中，并说明面试包含 AI 练习或讨论。这是一个具体岗位的证据，不支持“所有销售岗位都已如此”或“未来一定怎样”的结论。',
      '本课建议将岗位要求分为已有证据、需要补充和需要向招聘方确认三类。案例用“背景—责任—判断—行动—结果—反思”讲述，区分团队结果和自己的贡献。没有完整结果时，诚实说明尚未验证之处，比补一个漂亮数字更可靠。',
      '作品也要标清身份：公开资料研究、虚构演示和真实部署是不同证据。用虚构知识库说明权限与评测，可以展示理解，但不能写成服务过真实客户。旧手册的倒计时计划可作为个人安排参考，天数不是掌握能力或拿到录用的保证。',
    ],
    example: {
      scene: '虚构示例：企业软件销售应聘 AI 客户岗位。行业背景待补。',
      input: '当前岗位原页、一份去标识化真实经历提纲，以及明确标注虚构的售后问答练习。',
      ai: '帮助映射岗位要求、检查表达是否清楚，并提出可能被追问的问题；不补造业绩和履历。',
      human: '本人确认每个事实、责任与数字，说明哪些是做过的工作，哪些只是学习成果。',
      next: '面试时用案例说明判断，再询问该岗位的成功标准、协作边界和入职后的优先事项。',
      conditions: '招聘页可能更新或下线；保留核对日期。真实资料应按保密要求处理，不提交客户名称和敏感附件。',
    },
    judgments: [
      '一个岗位样本可以提供准备方向，不能代表完整劳动力市场、薪酬趋势或录用概率。',
      '回答结构帮助表达，不是可冒充本人经历的标准答案；没有做过就明确说是分析或练习。',
    ],
    steps: [
      { title: '先解释岗位结果', detail: '不用复述整份招聘要求，说清这个岗位要为谁解决什么问题。' },
      { title: '可选证据练习', detail: '用能力差距工具整理一条真实经历和一个待补项，也可以只口头复述；不要求上传材料。' },
    ],
    takeaway: '把自己做过什么和怎样判断说清楚，比把未来说得很确定更有说服力。',
    quiz: { question: '完成一个虚构 AI 演示后，能否在简历中写“已推动企业客户 AI 生产落地”？', answer: '不能。应写清这是教学演示、个人研究或公开资料作品，并说明展示了哪些判断。生产落地需要真实部署、责任与使用证据，不能由作品形式替代。' },
    sources: [sources.gleanRole],
    topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    toolIds: ['company-role-research', 'role-gap-analysis', 'transition-evidence'],
    relatedItemIds: ['ST-019', 'ST-021', 'ST-030'],
    legacySections: ['definition', 'profile', 'preparation', 'answering', 'questions', 'interview-day', 'sources'],
  },
];
