import type {
  ConclusionScope,
  DeeperAnalysis,
  EvidenceLevel,
  EvidenceRef,
  KnowledgeDomain,
  RiskLevel,
  SeedCandidate,
  SeedContentCategory,
  SeedReview,
} from '../domain';

const OWNER_APPROVED_AT = '2026-08-24T04:39:04.000Z';

interface EvidenceInput {
  readonly sourceId: string;
  readonly title: string;
  readonly publisher: string;
  readonly url: string;
  readonly publishedAt: string;
  readonly level: EvidenceLevel;
  readonly language?: 'zh' | 'en';
  readonly dateBasis?: EvidenceRef['dateBasis'];
}

interface SupportingFactInput {
  readonly statement: string;
  readonly evidenceIndexes: readonly number[];
}

interface CandidateInput {
  readonly id: string;
  readonly slug: string;
  readonly seedCategory: SeedContentCategory;
  readonly conclusionScope: ConclusionScope;
  readonly title: string;
  readonly originalTitle?: string;
  readonly summary: string;
  readonly kind: SeedCandidate['kind'];
  readonly domains: readonly KnowledgeDomain[];
  readonly topicSlugs: readonly string[];
  readonly tags: readonly string[];
  readonly toolIds: readonly string[];
  readonly audience?: SeedCandidate['audience'];
  readonly publishedAt: string;
  readonly freshness: SeedCandidate['freshness'];
  readonly whyItMatters: string;
  readonly salesImplication: string;
  readonly roleOrgImplication: string;
  readonly nextAction: string;
  readonly evidence: readonly EvidenceInput[];
  readonly supportingFacts: readonly SupportingFactInput[];
  readonly deeperAnalysis: DeeperAnalysis;
  readonly riskLevel: RiskLevel;
  readonly changeWindow: SeedReview['changeWindow'];
  readonly factType: SeedReview['factType'];
  readonly verificationNotes: string;
}

function defineCandidate(input: CandidateInput): SeedCandidate {
  const evidence = input.evidence.map((item, index) => ({
    id: `${input.id}-e${index + 1}`,
    sourceId: item.sourceId,
    title: item.title,
    publisher: item.publisher,
    url: item.url,
    publishedAt: item.publishedAt,
    level: item.level,
    language: item.language ?? 'en',
    allowlisted: true,
    dateBasis: item.dateBasis ?? 'published',
  }));

  return {
    id: input.id,
    slug: input.slug,
    seedCategory: input.seedCategory,
    conclusionScope: input.conclusionScope,
    supportingFacts: input.supportingFacts.map((fact, index) => ({
      id: `${input.id}-f${index + 1}`,
      statement: fact.statement,
      evidenceIds: fact.evidenceIndexes.map((evidenceIndex) => `${input.id}-e${evidenceIndex}`),
    })),
    deeperAnalysis: input.deeperAnalysis,
    title: { zh: input.title },
    originalTitle: input.originalTitle,
    summary: { zh: input.summary },
    kind: input.kind,
    domains: input.domains,
    topicSlugs: input.topicSlugs,
    tags: input.tags,
    toolIds: input.toolIds,
    audience: input.audience ?? ['transitioning_seller', 'ai_ae', 'solution'],
    publishedAt: input.publishedAt,
    updatedAt: OWNER_APPROVED_AT,
    freshness: input.freshness,
    whyItMatters: { zh: input.whyItMatters },
    salesImplication: { zh: input.salesImplication },
    roleOrgImplication: { zh: input.roleOrgImplication },
    nextAction: { zh: input.nextAction },
    evidence,
    relatedItemIds: [],
    editorialStatus: 'approved',
    riskLevel: input.riskLevel,
    publicationMode: 'manual',
    seedContent: true,
    audit: {
      sourceFingerprint: `source-ref:${input.slug}:2026-08-24`,
      ruleVersion: 'saas-602-owner-approved-v1',
      processedAt: OWNER_APPROVED_AT,
      releaseVersion: 'seed-public-v1-2026-08-24',
      rollbackState: 'available',
    },
    review: {
      status: 'approved',
      verifiedAt: OWNER_APPROVED_AT,
      changeWindow: input.changeWindow,
      factType: input.factType,
      verificationNotes: input.verificationNotes,
    },
  };
}

export const approvedSeedItems = [
  defineCandidate({
    id: 'ST-001', slug: 'frontier-model-price-performance', seedCategory: 'ai_technology', conclusionScope: 'cross_organization',
    title: '模型价格性能比正在重写企业选型账本',
    originalTitle: 'Advancing the price-performance frontier with GPT-5.6',
    summary: 'OpenAI 调整 GPT-5.6 产品价格的同时，腾讯混元按不同模型公布差异化 Token 单价。企业选型正在从“最强模型”转向单位有效任务的综合成本。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales'], topicSlugs: ['agent-business-model', 'ai-poc-scale'],
    tags: ['模型成本', '价格性能比', '单位任务成本'], toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'],
    publishedAt: '2026-07-30T10:00:00.000Z', freshness: 'current',
    whyItMatters: 'Token 降价只降低输入成本的一部分；准确率、重试、人工复核、容量和延迟共同决定业务最终花费。',
    salesImplication: '报价讨论应使用“每个合格结果的总成本”，并同时展示基准模型、轻量模型和人工流程。',
    roleOrgImplication: '销售、解决方案和财务需要共同维护成本假设，避免技术榜单替代客户自己的经济模型。',
    nextAction: '选一个客户任务，分别计算模型费、失败重试、人工复核和容量保障，形成三档选型表。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Advancing the price-performance frontier with GPT-5.6', publisher: 'OpenAI', url: 'https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6', publishedAt: '2026-07-30T10:00:00.000Z', level: 'official' },
      { sourceId: 'tencent-cloud-ai', title: '混元大模型计费概述', publisher: '腾讯云', url: 'https://cloud.tencent.com/document/product/1729/97731', publishedAt: '2026-06-26T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 官方公告把 GPT-5.6 的降价与价格性能边界改善放在同一产品叙事中。', evidenceIndexes: [1] },
      { statement: '腾讯云按混元不同模型公布每百万 Token 的差异化价格，并区分资源包与后付费顺序。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '模型分层和降价让更多任务跨过经济可行线，但失败重试与人工复核会把名义低价重新放大为真实任务成本。',
      businessValue: '按合格结果核算后，企业可以把模型投入与处理量、交付时长和毛利连接，减少只按 Token 采购造成的错配。',
      boundary: '价格性能比不是稳定常数；任务难度、地区、上下文长度、容量和厂商调价都会改变结论，必须用客户任务集复测。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '已按终审意见增加中国大陆厂商事实；价格属于高频变化信息，发布前须重新打开两方计费页核价。',
  }),
  defineCandidate({
    id: 'ST-002', slug: 'ultrafast-inference-service-tier', seedCategory: 'ai_technology', conclusionScope: 'cross_organization',
    title: '推理速度开始成为可单独采购的服务层',
    originalTitle: 'Previewing Ultrafast mode: GPT-5.6 Sol at up to 14X the speed',
    summary: 'OpenAI 预览 Ultrafast 服务层，阿里云百炼 Prime 快速模式也将更高 TPS 作为单独计费能力。速度正在从模型附属指标变成可选服务等级。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales'], topicSlugs: ['agent-business-model', 'ai-poc-scale'],
    tags: ['推理速度', '服务等级', 'TPS', 'SLA'], toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'],
    publishedAt: '2026-08-13T10:00:00.000Z', freshness: 'breaking',
    whyItMatters: '当推理位于客服、语音、编码 Agent 或多步流程的关键路径上，等待会阻断下一步并累积为整体流程时长。',
    salesImplication: '不要只演示峰值速度；要把首 Token 延迟、持续 TPS、并发、稳定性和加速溢价写进同一验收表。',
    roleOrgImplication: 'AI 商业岗位需要把技术速度换算为等待时间、完成率、坐席产能和客户体验，而不是复述基准数字。',
    nextAction: '为一个实时场景测算标准层与快速层对单次等待、每日完成量和单位任务成本的影响。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Previewing Ultrafast mode: GPT-5.6 Sol at up to 14X the speed', publisher: 'OpenAI', url: 'https://openai.com/index/previewing-ultrafast', publishedAt: '2026-08-13T10:00:00.000Z', level: 'official' },
      { sourceId: 'aliyun-model-studio', title: 'Prime 快速模式', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/fast-mode', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 将 Ultrafast 作为预览服务层，并宣称 GPT-5.6 Sol 最高达到原服务 14 倍速度和每秒 750 个输出 Token。', evidenceIndexes: [1] },
      { statement: '阿里云百炼把 Prime 快速模式作为单独能力，称 TPS 为标准 API 的 1.5 至 2 倍并按 Token 单独计费。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '实时任务中的每次等待都会延迟后续工具调用和人工决策；多步 Agent 流程还会把单步延迟串联累加。',
      businessValue: '更短等待可提高会话完成率、缩短坐席处理时长、增加单位时间内完成的工作循环，因此企业愿意为关键路径购买确定的速度等级。',
      boundary: '离线批处理、低频任务或人工审核占主导的流程未必值得加速；若准确率、可用性或价格恶化，纯速度提升不能单独证明 ROI。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '已用 OpenAI 与阿里云两个独立厂商动作验证服务层现象；性能数字均为厂商自述，仍需客户负载实测。',
  }),
  defineCandidate({
    id: 'ST-003', slug: 'data-retention-controls', seedCategory: 'ai_technology', conclusionScope: 'cross_organization',
    title: '企业模型服务正在细化数据保留控制',
    originalTitle: 'Offering Zero Data Retention for frontier models',
    summary: 'OpenAI 为符合条件的 API 客户提供 Zero Data Retention；Anthropic 公开默认保留周期、例外和可约定的零保留机制。数据边界正从一句承诺变成可谈判的产品与合同配置。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales', 'role_org'], topicSlugs: ['ai-trust-governance', 'ai-buying-committee'],
    tags: ['数据保留', 'ZDR', '企业采购', '隐私'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'],
    publishedAt: '2026-08-19T19:00:00.000Z', freshness: 'breaking',
    whyItMatters: '企业真正关心的是哪些数据在何处、保留多久、因何例外被保存，以及谁能用合同和日志验证。',
    salesImplication: '发现阶段要逐层确认输入、输出、日志、安全检测和删除，而不能把“不会训练”误写成“不会存储”。',
    roleOrgImplication: '销售需要联动安全、法务和产品，建立数据流图、适用套餐、例外条款和持续核验责任。',
    nextAction: '把一个场景拆成采集、传输、推理、日志、安全检测和删除六段，并为每段写责任人与证据。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Offering Zero Data Retention for frontier models', publisher: 'OpenAI', url: 'https://openai.com/index/offering-zero-data-retention-for-frontier-models', publishedAt: '2026-08-19T19:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-news', title: "How long do you store my organization's data?", publisher: 'Anthropic Privacy Center', url: 'https://privacy.claude.com/en/articles/7996866-how-long-do-you-store-my-organization-s-data', publishedAt: '2026-07-01T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 公告称符合条件的 API 客户可使用 Zero Data Retention，并说明安全处理存在资格与配置边界。', evidenceIndexes: [1] },
      { statement: 'Anthropic 隐私说明列出 API 输入输出通常在 30 天内删除，同时说明安全违规等例外及可签署零保留安排。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '可配置保留期把抽象隐私承诺转化为采购可检查的技术设置、合同义务和异常处理。',
      businessValue: '边界更清楚可减少安全问卷往返和法务不确定性，让原本因敏感数据停滞的场景进入受控试点。',
      boundary: '零保留不自动覆盖客户端日志、第三方工具、违规调查或所有产品套餐；最终结论必须以客户合同和实际数据流为准。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '已增加第二家模型厂商的独立政策事实；本条只解释采购问题，不提供隐私或法律结论。',
  }),
  defineCandidate({
    id: 'ST-004', slug: 'contract-first-agent-delegation', seedCategory: 'ai_technology', conclusionScope: 'cross_organization',
    title: '多 Agent 协作要先把工作拆成可验证契约',
    originalTitle: 'How agents can delegate better',
    summary: 'Google Cloud 强调可验证子任务、成本匹配和最小权限；Anthropic 区分固定 Workflow 与自主 Agent，并建议先用简单、可组合模式。两者共同指向契约优先。',
    kind: 'explainer', domains: ['ai_technology', 'enterprise_sales', 'role_org'], topicSlugs: ['agent-business-model', 'ai-trust-governance'],
    tags: ['Multi-Agent', '任务契约', '可验证性', '最小权限'], toolIds: ['poc-success-canvas', 'stakeholder-adoption-risk'],
    publishedAt: '2026-08-21T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '复杂目标若不能拆成有输入、输出和验收标准的子任务，错误会沿委派链扩散并难以定位。',
    salesImplication: '演示应展示任务合同、失败处理和人工升级点，而不是把“自动完成”包装成不可审计黑箱。',
    roleOrgImplication: '业务专家负责验收语义，工程负责运行边界，安全负责权限；三者缺一都会让 Multi-Agent 停留在演示。',
    nextAction: '选择一个三步流程，为每一步写输入、输出、权限、验收人和失败升级条件。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: 'How agents can delegate better', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/how-agents-can-delegate-better', publishedAt: '2026-08-21T00:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-news', title: 'Building effective agents', publisher: 'Anthropic', url: 'https://www.anthropic.com/engineering/building-effective-agents', publishedAt: '2024-12-19T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'Google Cloud 建议将目标拆成可可靠验证的子任务，并按成本匹配模型、限制数据权限、保留人类判断点。', evidenceIndexes: [1] },
      { statement: 'Anthropic 区分预定义 Workflow 与自主 Agent，指出 Agent 通常以更高延迟和成本换取任务表现。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '任务契约把开放目标变成可观测接口，使错误可在单步被发现、重试或升级，而不是在终点才暴露。',
      businessValue: '可局部验收降低返工和审计成本，也让企业可以逐步扩大自动化范围而非一次承担全流程风险。',
      boundary: '高度模糊、依赖隐性经验或缺少客观验收标准的任务仍需专家主导；增加 Agent 数量不会自动提高可靠性。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '两篇官方工程材料来自不同厂商；方法建议不是统一标准，需在客户任务中验证。',
  }),
  defineCandidate({
    id: 'ST-005', slug: 'customer-task-evaluation-over-benchmarks', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '模型评测必须从通用榜单转向客户任务集',
    summary: 'Stanford AI Index 显示能力进步并不均匀，阿里云百炼同时提供人工、自动和基准评测。选型真正需要回答的是模型能否稳定完成客户自己的高价值任务。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology'], topicSlugs: ['ai-poc-scale', 'agent-business-model'],
    tags: ['模型评测', '客户任务集', '失败分布'], toolIds: ['poc-success-canvas', 'value-hypothesis-one-pager'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '综合榜单会平均掉行业术语、长流程、容错要求和人工恢复成本，无法直接代表某个业务场景。',
    salesImplication: 'POC 前应与客户共同定义代表性任务、失败类型、复核规则和基线，而不是先选模型再寻找价值。',
    roleOrgImplication: '业务专家拥有任务与正确性定义，技术团队负责评测执行，销售负责把结果连接到经济价值。',
    nextAction: '收集 20 个真实但脱敏的客户任务，标注合格、可修复和不可接受三类结果。',
    evidence: [
      { sourceId: 'stanford-ai-index-2026', title: '2026 AI Index Report', publisher: 'Stanford HAI', url: 'https://hai.stanford.edu/ai-index/2026-ai-index-report', publishedAt: '2026-04-06T00:00:00.000Z', level: 'multi_source' },
      { sourceId: 'aliyun-model-studio', title: '模型评测概述', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/model-evaluation-overview', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'Stanford AI Index 报告显示部分 Agent 基准显著进步，但结构化任务仍存在大约三分之一失败，能力边界呈现不均匀。', evidenceIndexes: [1] },
      { statement: '阿里云百炼官方文档提供人工评测、自动评测和基准评测等路径，允许围绕具体数据集比较模型。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '客户任务集把模型能力映射到业务输入、容错与复核流程，暴露平均分遮蔽的高损失失败。',
      businessValue: '企业可以据此选择更便宜但足够好的模型、确定人工兜底，并以真实成功率计算 POC 是否值得扩展。',
      boundary: '任务集过小、过于干净或由供应商挑选会制造假绿；需要覆盖边缘案例并定期随业务变化更新。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '原暂不发布内容已按终审意见替换为面向销售决策的评测方法，并增加大陆平台的可操作事实。',
  }),
  defineCandidate({
    id: 'ST-006', slug: 'enterprise-agent-control-plane', seedCategory: 'ai_technology', conclusionScope: 'cross_organization',
    title: '企业 Agent 平台正在补齐统一控制面',
    summary: 'Google Gemini Enterprise 把身份、网关、模拟和可观测性放进平台；阿里云 Agent Identity 则聚焦身份、凭据和权限。企业级差异开始从“能运行”转向“能被治理”。',
    kind: 'update', domains: ['ai_technology', 'role_org', 'enterprise_sales'], topicSlugs: ['ai-trust-governance', 'workflow-adoption'],
    tags: ['Agent 平台', '身份', '权限', '可观测性'], toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'],
    publishedAt: '2026-04-22T00:00:00.000Z', freshness: 'current',
    whyItMatters: 'Agent 一旦连接企业数据和工具，就需要像账号与应用一样被识别、授权、监控和撤销。',
    salesImplication: '平台演示必须覆盖身份、最小权限、测试、日志和下线，不应只展示一次成功执行。',
    roleOrgImplication: '业务负责人、平台团队和安全团队需要共同拥有 Agent 生命周期，而不是把责任全部留给开发者。',
    nextAction: '为一个 Agent 画出身份、凭据、工具权限、日志、暂停和下线六个控制点。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' },
      { sourceId: 'aliyun-model-studio', title: 'Agent Identity 产品文档', publisher: '阿里云', url: 'https://help.aliyun.com/zh/agentidentity/', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Google Gemini Enterprise 官方材料列出 Agent 身份、网关、模拟、可观测性与统一治理能力。', evidenceIndexes: [1] },
      { statement: '阿里云 Agent Identity 官方文档提供 Agent 身份、凭据和访问第三方 SaaS 的权限管理。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '统一控制面把分散在代码、密钥和日志中的治理动作集中为可追踪生命周期，减少影子 Agent 和长期权限残留。',
      businessValue: '治理能力降低接入新系统、审计和事故处置的边际成本，使更多高价值但敏感的流程具备上线条件。',
      boundary: '购买平台不等于治理完成；身份映射、业务责任、数据分类和人工响应仍需企业自己设计与执行。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '控制面趋势由国际与中国大陆两个官方产品事实共同支持；能力可用性和地区范围需采购时复核。',
  }),
  defineCandidate({
    id: 'ST-007', slug: 'api-compatibility-does-not-remove-switching-cost', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '接口兼容降低迁移门槛，但不会消除模型切换成本',
    summary: '阿里云百炼和腾讯混元都提供 OpenAI 兼容调用方式，说明接口兼容已成为迁移抓手；但提示词、评测、数据地域、限额和计费仍然不同。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology'], topicSlugs: ['agent-business-model', 'ai-poc-scale'],
    tags: ['API 兼容', '模型迁移', '锁定成本'], toolIds: ['discovery-interview', 'poc-success-canvas'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '相同 API 形状只能减少代码改造，无法保证输出行为、工具调用、配额、价格和合规边界一致。',
    salesImplication: '不要承诺“一键切换”；应把迁移拆成接口、提示词、评测、数据、运维和合同六项成本。',
    roleOrgImplication: '采购与架构团队需要把可替换性写入验收，并持续保留跨模型回归测试。',
    nextAction: '选择同一组任务在两个兼容接口上运行，记录代码改动、结果差异、失败类型和总成本。',
    evidence: [
      { sourceId: 'aliyun-model-studio', title: '什么是阿里云百炼 Model Studio', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/what-is-model-studio', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
      { sourceId: 'tencent-cloud-ai', title: 'OpenAI 兼容接口', publisher: '腾讯云混元', url: 'https://cloud.tencent.com/document/product/1729/111007', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: '阿里云百炼官方文档提供 OpenAI 兼容 API，同时说明不同地域使用不同 Base URL、API Key、模型和价格。', evidenceIndexes: [1] },
      { statement: '腾讯混元官方文档提供 OpenAI 兼容接口，帮助已有调用代码接入混元模型。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '接口兼容统一了请求外形，却没有统一模型语义、工具行为、内容策略和运营条件，因此切换成本从代码层转移到验证层。',
      businessValue: '企业可以用兼容层降低初次试用和多供应商接入成本，但只有保留回归评测才能真正获得议价与容灾能力。',
      boundary: '若应用深度依赖厂商专属缓存、工具、微调或安全能力，兼容 API 的替换价值会明显下降。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '原“常识型”内容已替换为中国大陆两家平台的具体迁移判断；兼容范围需按实际 SDK 和功能逐项验证。',
  }),
  defineCandidate({
    id: 'ST-008', slug: 'capability-and-responsibility-evidence', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: 'AI 项目验收要同时交付能力证据与责任证据',
    summary: 'Stanford AI Index 记录能力采用扩张与责任披露落差；NIST AI RMF 要求围绕治理、测量和管理建立风险活动。项目不能只证明“做得到”，还要证明“谁负责、如何发现问题”。',
    kind: 'method', domains: ['role_org', 'enterprise_sales', 'ai_technology'], topicSlugs: ['ai-trust-governance', 'ai-poc-scale'],
    tags: ['责任证据', '风险治理', '验收'], toolIds: ['poc-success-canvas', 'stakeholder-adoption-risk'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '能力演示证明顺利路径，责任证据则覆盖失败发现、人工接管、记录和改进，决定系统能否持续运营。',
    salesImplication: 'POC 交付物应同时包含任务结果、失败样本、日志、责任矩阵和暂停条件。',
    roleOrgImplication: '业务、风险、技术和管理者要在上线前明确各自的决策权与响应责任。',
    nextAction: '给现有 POC 增加一页责任验收：监控人、升级人、停用人、复盘周期和证据位置。',
    evidence: [
      { sourceId: 'stanford-ai-index-2026', title: '2026 AI Index Report', publisher: 'Stanford HAI', url: 'https://hai.stanford.edu/ai-index/2026-ai-index-report', publishedAt: '2026-04-06T00:00:00.000Z', level: 'multi_source' },
      { sourceId: 'nist-ai-rmf', title: 'AI Risk Management Framework', publisher: 'NIST', url: 'https://www.nist.gov/itl/ai-risk-management-framework', publishedAt: '2023-01-26T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'Stanford AI Index 指出组织对能力和使用的披露增长快于负责任 AI 实践披露，并记录 AI 事件数量上升。', evidenceIndexes: [1] },
      { statement: 'NIST AI RMF 以 Govern、Map、Measure、Manage 四类活动组织自愿风险管理工作。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '把责任写成证据要求，会迫使团队在上线前设计监控、升级和退出，从源头减少“人人参与、无人负责”。',
      businessValue: '责任证据缩短风险审批和事故定位时间，也保护 POC 成功后的扩展节奏，避免一次失败导致整体停摆。',
      boundary: '框架清单不能替代具体责任人的能力和资源；低风险内部辅助场景可采用更轻的证据强度。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '研究趋势与官方风险框架相互补充；NIST AI RMF 为自愿框架，不得表述为普遍法律义务。',
  }),
  defineCandidate({
    id: 'ST-009', slug: 'agent-evaluation-failure-recovery-cost', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: 'Agent 评测要看失败分布和人工恢复成本',
    summary: 'Stanford 报告显示结构化任务仍存在显著失败；阿里云百炼提供多种评测方式。平均成功率之外，高损失失败和人工修复时间更接近企业真实风险。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    tags: ['Agent 评测', '失败分布', '人工恢复'], toolIds: ['poc-success-canvas', 'value-hypothesis-one-pager'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '两套平均分相近的系统，可能分别表现为大量轻微错误和少量灾难性错误，业务后果完全不同。',
    salesImplication: '验收要按失败类型、损失和可恢复性分层，并把人工修复分钟数计入单位任务成本。',
    roleOrgImplication: '业务专家定义损失等级，运营团队记录恢复路径，技术团队定位可修复的系统原因。',
    nextAction: '对 50 次运行建立失败台账，至少标出频率、损失、发现方式、恢复分钟数和责任人。',
    evidence: [
      { sourceId: 'stanford-ai-index-2026', title: '2026 AI Index Report — Technical Performance', publisher: 'Stanford HAI', url: 'https://hai.stanford.edu/ai-index/2026-ai-index-report', publishedAt: '2026-04-06T00:00:00.000Z', level: 'multi_source' },
      { sourceId: 'aliyun-model-studio', title: '模型评测概述', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/model-evaluation-overview', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'Stanford AI Index 报告称 OSWorld 等 Agent 基准明显进步，但结构化基准仍有约三分之一任务失败。', evidenceIndexes: [1] },
      { statement: '阿里云百炼提供人工、自动与基准评测路径，使团队可以对自有数据集记录模型表现。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '失败分类把不可见的尾部风险和恢复劳动显性化，使平均准确率不再掩盖高损失事件。',
      businessValue: '企业可据此设计人工兜底、限定使用范围，并比较自动化节省与新增恢复成本，得到更可信的 ROI。',
      boundary: '评测环境若缺少真实工具、权限和用户行为，恢复成本会被低估；高风险决策还需更严格的独立验证。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '结论由独立研究指标与大陆平台评测能力共同支撑；不把单一基准等同于生产表现。',
  }),
  defineCandidate({
    id: 'ST-010', slug: 'prototype-to-production-three-gates', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '原型到生产要经过接入、规模与治理三道门',
    summary: 'Google Cloud 把创业团队常见问题归纳为 Onboard、Scale、Govern；腾讯云 ADP 则把 Workflow、Multi-Agent、知识、工具和平台管理放进企业 Agent 开发平台。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale', 'workflow-adoption'],
    tags: ['生产化', '规模化', '治理'], toolIds: ['poc-success-canvas', 'ai-maturity-scan'],
    publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '能调用 API 只解决接入；容量、身份、可观测、知识维护和责任边界决定能否长期运行。',
    salesImplication: '商机阶段要分别确认接入条件、规模负载和治理要求，并把缺口写进 POC 退出标准。',
    roleOrgImplication: '产品、平台、安全和业务运营应分阶段进入，而不是在签约后才补治理。',
    nextAction: '把当前机会分成接入、规模、治理三列，每列写已知证据、最大未知和责任人。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: '10 questions for your startup developers', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
      { sourceId: 'tencent-cloud-ai', title: '腾讯云智能体开发平台 ADP', publisher: '腾讯云', url: 'https://cloud.tencent.com/document/product/1759', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Google Cloud 将从原型走向生产的问题分为接入、规模和治理，并列出密钥、429、计费、可观测和预留容量等检查项。', evidenceIndexes: [1] },
      { statement: '腾讯云 ADP 官方文档覆盖 Workflow、Multi-Agent、知识、工具和平台管理等企业开发能力。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '三道门把“技术可行”拆解为不同失败模式，避免团队用一次演示同时替代容量、运营和治理验证。',
      businessValue: '分门验收可更早发现扩容或合规成本，减少签约后返工，并让客户按风险逐步投入。',
      boundary: '小范围、低风险、无外部系统写入的工具可简化门槛；涉及关键决策或敏感数据时不能跳过治理门。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '方法来自 Google 工程检查项与腾讯大陆企业平台能力的交叉归纳，不代表两家采用同一成熟度标准。',
  }),
  defineCandidate({
    id: 'ST-011', slug: 'production-constraints-in-discovery', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '发现阶段就要问清生产约束',
    summary: 'Google Cloud 把身份、容量、计费和可观测列为生产问题；阿里云百炼明确不同地域拥有独立 Base URL、API Key、模型和价格。生产限制不是签约后的技术细节。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology'], topicSlugs: ['ai-buying-committee', 'ai-poc-scale'],
    tags: ['需求发现', '生产约束', '地域'], toolIds: ['discovery-interview', 'poc-success-canvas'],
    publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '地域、身份、配额和日志如果与客户现状不匹配，再好的业务场景也可能无法进入生产。',
    salesImplication: '首次技术发现就应问数据地域、身份方式、峰值负载、日志要求、预算和故障响应。',
    roleOrgImplication: '销售负责暴露未知，解决方案负责验证约束，客户平台和安全团队负责给出准入条件。',
    nextAction: '在下一次发现访谈加入六个生产问题，并把“未确认”作为显式风险而非默认可行。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: '10 questions for your startup developers', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
      { sourceId: 'aliyun-model-studio', title: '什么是阿里云百炼 Model Studio', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/what-is-model-studio', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'Google Cloud 官方文章把 API Key 与 IAM、429 与容量、账单、模型可观测和预留容量列为生产前问题。', evidenceIndexes: [1] },
      { statement: '阿里云百炼说明中国内地、新加坡等地域分别使用不同 Base URL、API Key、可用模型和定价。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '把约束前移会在需求仍可调整时暴露不可行条件，避免方案在后期被基础设施或安全审批推翻。',
      businessValue: '更早识别硬门槛能提高机会预测准确性、减少无效 POC，并让报价包含真实生产成本。',
      boundary: '早期探索不需要一次回答全部问题，但关键未知必须有责任人和验证日期，不能被乐观假设覆盖。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '两方材料分别支持生产检查项和大陆地域约束；具体可用区、模型与价格需实时复核。',
  }),
  defineCandidate({
    id: 'ST-012', slug: 'poc-success-four-gates', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: 'POC 成功要同时通过价值、质量、运营与治理四道门',
    summary: '阿里云百炼提供多种模型评测，Google Cloud 则把容量、身份、计费和可观测列为生产化问题。只有模型得分而没有业务和运营证据的 POC 仍不完整。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    tags: ['POC 成功', '四道门', '规模化'], toolIds: ['poc-success-canvas', 'value-hypothesis-one-pager'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '质量过线不等于客户愿意采用，价值过线也不等于系统能被安全运营。四类证据缺一都会阻断扩展。',
    salesImplication: '在 POC 启动前与客户共同写出四类阈值、证据所有者和失败后的决策。',
    roleOrgImplication: '业务、技术、运营和风险负责人要共同签署成功定义，避免项目结束时各自解释。',
    nextAction: '把现有 POC 成功标准分成价值、质量、运营、治理四栏，删除无法被观察的形容词。',
    evidence: [
      { sourceId: 'aliyun-model-studio', title: '模型评测概述', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/model-evaluation-overview', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
      { sourceId: 'google-cloud-ai-blog', title: '10 questions for your startup developers', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: '阿里云百炼把人工、自动和基准评测作为模型评估方式，支持围绕具体数据集检查质量。', evidenceIndexes: [1] },
      { statement: 'Google Cloud 把身份、容量、计费与模型可观测列为从原型进入生产必须回答的问题。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '四道门把“成功”分解到不同决策者，使质量结果、业务收益和生产责任在同一时点被验证。',
      businessValue: '完整成功标准可以减少无结论 POC，提前形成扩展预算、上线计划和风险条件，提高试点转生产概率。',
      boundary: '四门权重随场景变化；低风险内部工具可轻量化治理，但不能用一个综合分掩盖任何硬性否决项。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '四道门是基于两方事实的编辑方法，不是厂商原文框架；应由客户共同定义阈值。',
  }),
  defineCandidate({
    id: 'ST-013', slug: 'ai-buying-committee-accountability', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: 'AI 采购委员会要围绕责任而不是部门名单组织',
    summary: 'NIST AI RMF 把治理贯穿风险活动；Google 企业 Agent 平台把身份、策略和可观测纳入控制面。采购讨论需要明确谁批准、谁运营、谁承担失败后果。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['ai-buying-committee', 'ai-trust-governance'],
    tags: ['采购委员会', '责任矩阵', '决策链'], toolIds: ['stakeholder-adoption-risk', 'discovery-interview'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '仅知道 IT、业务和法务参与，不足以判断项目如何做出批准、暂停、升级和下线决定。',
    salesImplication: '关系图应从“谁参会”升级为“谁拥有哪项决定、需要什么证据、承担什么风险”。',
    roleOrgImplication: '决策权与执行责任要配对，避免业务赞成、技术实施、风险部门最后否决的断裂。',
    nextAction: '为机会画四类责任：价值批准、技术准入、风险接受、运营接管，并为每类指定证据。',
    evidence: [
      { sourceId: 'nist-ai-rmf', title: 'AI Risk Management Framework', publisher: 'NIST', url: 'https://www.nist.gov/itl/ai-risk-management-framework', publishedAt: '2023-01-26T00:00:00.000Z', level: 'official' },
      { sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'NIST AI RMF 把 Govern 设为贯穿风险映射、测量和管理的治理职能。', evidenceIndexes: [1] },
      { statement: 'Google Gemini Enterprise 官方材料把 Agent 身份、策略、模拟和可观测放进统一控制面。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '按责任组织委员会，会把抽象关注点转化为明确决策和证据需求，减少后期才出现的隐藏否决者。',
      businessValue: '销售可更准确预测决策路径、减少重复沟通，并围绕每位责任人的风险和收益形成差异化材料。',
      boundary: '责任图不是静态组织架构；大型客户中同一责任可能分布在集团、区域和业务线，需要持续核实实际权力。',
    },
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'editorial_inference',
    verificationNotes: '责任型委员会是编辑方法；NIST 为自愿框架，Google 能力为厂商自述，均不替代客户实际治理制度。',
  }),
  defineCandidate({
    id: 'ST-014', slug: 'ai-value-evidence-ladder', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: 'AI 价值证据要从演示逐级走到运营指标',
    summary: 'OpenAI 企业采用材料强调从辅助走向执行；Google Cloud 把生产可观测和计费列为规模化问题。价值证据也应从“能做”升级为“持续做、值得做”。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['ai-poc-scale', 'workflow-adoption'],
    tags: ['价值证据', '运营指标', '规模化'], toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'],
    publishedAt: '2026-08-12T06:00:00.000Z', freshness: 'current',
    whyItMatters: '一次演示只能证明可能性，无法证明用户持续采用、流程稳定运行或经济收益覆盖新增成本。',
    salesImplication: '使用证据阶梯：演示可行、任务合格、用户采用、流程指标改善、财务结果出现。',
    roleOrgImplication: '销售负责价值假设，客户成功负责采用和运营证据，财务与业务负责人确认最终收益。',
    nextAction: '为当前机会写五级证据阶梯，并标出现在处于哪一级、下一级需要谁提供数据。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'From assistance to execution: How enterprises put AI to work', publisher: 'OpenAI', url: 'https://openai.com/index/how-enterprises-put-ai-to-work', publishedAt: '2026-08-12T06:00:00.000Z', level: 'official' },
      { sourceId: 'google-cloud-ai-blog', title: '10 questions for your startup developers', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 企业材料把采用方向描述为从个人辅助扩展到更复杂的工作执行。', evidenceIndexes: [1] },
      { statement: 'Google Cloud 把账单、容量和模型可观测列为生产化检查项，表明持续运营需要独立证据。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '证据阶梯让每个阶段只回答一个更强问题，防止团队用低强度演示替代高强度业务证明。',
      businessValue: '客户可以按证据成熟度逐步释放预算，销售也能更早识别无法从试点跨越到运营的机会。',
      boundary: '财务结果常受季节、流程改造和人员变化影响；不能把相关性直接写成 AI 单独造成的因果。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '厂商采用叙事和生产检查项只用于构建证据阶梯，不把厂商案例效果外推为普遍收益。',
  }),
  defineCandidate({
    id: 'ST-015', slug: 'china-ai-opportunity-boundaries', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '中国企业 AI 商机要在 POC 前确认地域、数据与计费边界',
    summary: '阿里云百炼明确不同地域的 API、模型和价格相互独立，并说明调用数据的处理规则；腾讯混元则区分资源包、后付费和平台迁移安排。大陆客户的可行性必须落到具体服务区与合同。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-buying-committee', 'ai-trust-governance', 'ai-poc-scale'],
    tags: ['中国大陆', '数据边界', '计费', '地域'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '同一产品名在不同地域可能使用不同密钥、模型、价格和数据路径，试点环境与目标生产环境不一致会制造假成功。',
    salesImplication: '立项前确认生产地域、数据类别、套餐、预算上限、合同主体和未来迁移，不用国际材料替代大陆服务事实。',
    roleOrgImplication: '销售、云架构、安全、法务和财务必须共同确认边界，任何一方的默认假设都可能阻断上线。',
    nextAction: '为一个大陆客户填写地域—数据—计费三联表，并为每个空白项指定核验页面和负责人。',
    evidence: [
      { sourceId: 'aliyun-model-studio', title: '什么是阿里云百炼 Model Studio', publisher: '阿里云百炼', url: 'https://help.aliyun.com/zh/model-studio/what-is-model-studio', publishedAt: '2026-08-19T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
      { sourceId: 'tencent-cloud-ai', title: '混元大模型计费概述', publisher: '腾讯云', url: 'https://cloud.tencent.com/document/product/1729/97731', publishedAt: '2026-06-26T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: '阿里云百炼明确各地域使用不同 Base URL、API Key、模型和价格，并对团队版调用数据说明不用于模型训练。', evidenceIndexes: [1] },
      { statement: '腾讯混元官方计费文档区分免费额度、资源包和后付费，并披露向 TokenHub 迁移的服务安排。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '地域、数据和计费边界共同决定生产架构与单位经济；任一项在 POC 后变化都会触发重测、重审或重新报价。',
      businessValue: '前置确认可减少试点后无法迁移的沉没成本，让客户预算、数据审批和上线计划使用同一事实基线。',
      boundary: '官方网页不是合同替代物，个人版、企业版和不同服务条款可能不同；敏感数据场景必须由客户法务与安全确认。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '原暂不发布条目已替换为中国大陆客户可直接使用的商机检查法；条款与价格发布前必须再次核验。',
  }),
  defineCandidate({
    id: 'ST-016', slug: 'workflow-redesign-before-tool-demo', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '销售发现要先画工作流，再谈 AI 功能',
    summary: 'OpenAI 研究强调 AI 正在扩展人们完成的工作；Anthropic 工程方法则区分固定 Workflow 与自主 Agent。客户价值取决于任务如何重组，而不是功能列表有多长。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['workflow-adoption', 'agent-business-model'],
    tags: ['工作流发现', '任务重构', '采用'], toolIds: ['discovery-interview', 'value-hypothesis-one-pager'],
    publishedAt: '2026-07-27T00:00:00.000Z', freshness: 'current',
    whyItMatters: '如果不理解现有输入、判断、协作和异常，AI 功能只能叠加在旧流程上，新增更多切换与复核。',
    salesImplication: '发现访谈从“想要什么功能”改为“哪一步最慢、为何慢、谁判断、错误如何恢复”。',
    roleOrgImplication: '一线员工提供真实任务，经理调整指标与责任，技术团队再决定使用 Workflow 还是 Agent。',
    nextAction: '画一条现有流程，标出等待、重复录入、专家判断和返工，再选择一个最小重构点。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'How AI is expanding what people do at work', publisher: 'OpenAI', url: 'https://openai.com/index/how-ai-is-expanding-what-people-do-at-work', publishedAt: '2026-07-27T00:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-news', title: 'Building effective agents', publisher: 'Anthropic', url: 'https://www.anthropic.com/engineering/building-effective-agents', publishedAt: '2024-12-19T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 发布的工作研究把 AI 使用描述为扩展人们可完成的任务与工作范围。', evidenceIndexes: [1] },
      { statement: 'Anthropic 工程文章区分预定义 Workflow 与由模型动态决定步骤的 Agent，并建议从简单模式开始。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '先画工作流会暴露价值瓶颈和不可自动化判断，从而选择正确的自动化边界，避免功能与问题错配。',
      businessValue: '销售可以把价值量化到等待时间、返工和专家产能，也能更早获得真正使用者的采用条件。',
      boundary: '流程过度标准化可能压掉必要的人类判断；探索性、低频或高度政治化的工作不适合强行画成线性流程。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '两份材料支持“工作变化”和“系统形态”两个事实层；具体流程价值仍需客户现场发现。',
  }),
  defineCandidate({
    id: 'ST-017', slug: 'vendor-case-attribution', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '厂商案例要拆成事实、归因和待验证假设',
    summary: 'OpenAI 案例称 Stampli 使用 ChatGPT Work 后发布工时下降 68%；Google Cloud 的生产检查项提醒团队同时核对容量、计费和可观测。案例数字可以启发假设，但不能直接成为客户承诺。',
    kind: 'case', domains: ['enterprise_sales', 'role_org'], topicSlugs: ['ai-poc-scale', 'workflow-adoption'],
    tags: ['客户案例', '证据归因', '价值假设'], toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'],
    publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '案例通常缺少完整基线、共同变化和选择偏差，直接复制数字会制造不可信承诺。',
    salesImplication: '保留“谁说的、测了什么、在什么条件下”，再把结果改写为客户 POC 的待验证假设。',
    roleOrgImplication: '市场提供案例，销售控制归因，解决方案设计验证，客户共同决定能否迁移。',
    nextAction: '选一个厂商案例，把内容分成可核事实、企业自述归因、客户需验证条件三列。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Stampli cuts launch hours by 68% using ChatGPT Work', publisher: 'OpenAI', url: 'https://openai.com/index/stampli', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
      { sourceId: 'google-cloud-ai-blog', title: '10 questions for your startup developers', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 官方案例页称 Stampli 在其特定工作中使用 ChatGPT Work 后发布工时下降 68%，该数字属于企业案例自述。', evidenceIndexes: [1] },
      { statement: 'Google Cloud 生产检查项要求同时验证容量、账单和模型可观测，说明演示效果之外仍有运营条件。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '证据拆分会把案例的启发价值与因果强度分开，防止不同流程、数据和团队条件被忽略。',
      businessValue: '销售仍可用案例缩短客户理解时间，同时通过本地验证保护信任、报价和后续扩展。',
      boundary: '即使行业和流程相似，也不能默认复制效果；只有客户自己的基线与对照证据才能支持本地收益判断。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '68% 仅按 OpenAI 客户案例自述标识；第二来源用于补充生产边界，不作为数字的独立复现。',
  }),
  defineCandidate({
    id: 'ST-018', slug: 'trust-discovery-before-security-questionnaire', seedCategory: 'enterprise_sales_method', conclusionScope: 'cross_organization',
    title: '信任发现要早于安全问卷',
    summary: 'OpenAI 和 Anthropic 都公开数据保留控制与例外，说明企业关切已细化到资格、周期和安全处理。销售若等正式问卷才讨论信任，往往已错过方案调整窗口。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['ai-trust-governance', 'ai-buying-committee'],
    tags: ['信任发现', '数据保留', '安全问卷'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'],
    publishedAt: '2026-08-19T19:00:00.000Z', freshness: 'breaking',
    whyItMatters: '客户对数据、可解释、人工监督和退出的担忧会改变场景范围、架构和采购路径。',
    salesImplication: '首次发现就问不可接受的数据、决策和失败后果，并把未知留给专业团队确认。',
    roleOrgImplication: '销售负责尽早暴露风险，不负责替代安全或法务下结论；专业团队需要给出可验证证据。',
    nextAction: '在发现提纲加入数据、权限、监督、记录、退出五类信任问题，并禁止用“通常没问题”作答。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Offering Zero Data Retention for frontier models', publisher: 'OpenAI', url: 'https://openai.com/index/offering-zero-data-retention-for-frontier-models', publishedAt: '2026-08-19T19:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-news', title: "How long do you store my organization's data?", publisher: 'Anthropic Privacy Center', url: 'https://privacy.claude.com/en/articles/7996866-how-long-do-you-store-my-organization-s-data', publishedAt: '2026-07-01T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 将 Zero Data Retention 与客户资格、模型范围和安全处理条件关联。', evidenceIndexes: [1] },
      { statement: 'Anthropic 公布 API 数据通常保留周期、违规调查等例外和可约定的零保留机制。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '提前发现信任约束让团队在架构和场景仍可调整时选择脱敏、缩小权限或增加人工监督。',
      businessValue: '可减少安全问卷往返和后期否决，提升机会预测准确性，也避免销售做出无法兑现的承诺。',
      boundary: '销售提问不是合规评估；涉及法规、合同或高风险用途时必须升级给客户与供应商的专业人员。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '两家模型厂商的公开政策共同支持信任问题的颗粒度；本条不提供安全或法律结论。',
  }),
  defineCandidate({
    id: 'ST-019', slug: 'applied-ai-architect-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'Applied AI Architect 连接模型能力与客户生产环境',
    summary: 'Anthropic 在招多个 Applied AI Architect；阿里云也出现 AI Agent、MaaS 和大模型解决方案架构岗位。跨市场岗位共同要求把模型能力落到行业场景和生产约束。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map'],
    tags: ['Applied AI Architect', '解决方案架构', '售前'], toolIds: ['company-role-research', 'role-gap-analysis'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '岗位价值不在背诵模型参数，而在连接业务问题、数据、架构、评测和客户决策。',
    salesImplication: '传统大客户销售可迁移复杂发现和协调能力，但需补足技术边界、评测设计与生产约束。',
    roleOrgImplication: '该角色通常位于销售、工程和客户成功交界处，结果责任必须与纯商务和纯研发区分。',
    nextAction: '各选一份中外岗位，把前三项结果要求映射到自己的证据、缺口和 30 天补齐行动。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — Applied AI open roles', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — AI 解决方案架构师相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出多个 Applied AI Architect 岗位，覆盖企业技术、行业和合作伙伴方向。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可检索到 AI Agent、MaaS 与大模型方向的解决方案架构岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '模型产品变化快且客户环境差异大，组织需要一个角色把需求发现、方案取舍和生产验证连续起来。',
      businessValue: '减少商务与工程之间的翻译损耗，提升 POC 设计质量，并让技术风险在承诺前被识别。',
      boundary: '岗位名称不是统一标准；不同公司可能把同样工作放在售前、Applied AI 或解决方案工程团队。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '中外岗位均为 2026-08-23 观察快照；岗位可能变化，趋势只按跨公司角色组合谨慎归纳。',
  }),
  defineCandidate({
    id: 'ST-020', slug: 'forward-deployed-engineer-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'Forward Deployed Engineer 把实施前移到客户现场',
    summary: 'Anthropic 在招 Forward Deployed Engineer；阿里云招聘中可见商业技术工程师、MTE/BTE 等贴近客户场景的技术岗位。AI 价值实现正在压缩售前与交付之间的距离。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'ai-poc-scale'],
    tags: ['Forward Deployed Engineer', 'FDE', '客户共创'], toolIds: ['company-role-research', 'transition-evidence'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: 'AI 产品常需在客户数据、流程和系统中共同验证，单纯交付标准软件难以完成价值闭环。',
    salesImplication: '销售需要更早确认客户工程资源、共同成功标准和现场反馈节奏。',
    roleOrgImplication: 'FDE 类角色把产品反馈、方案实施和客户结果连接起来，但具体边界因公司而异。',
    nextAction: '比较 FDE、商业技术工程师和传统售前三类岗位，找出各自交付的结果而不是技能名词。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — Forward Deployed Engineer', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — 商业技术工程师与 MTE/BTE 相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出多个地区的 Forward Deployed Engineer 岗位。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可检索到多项商业技术工程师、MTE/BTE 和大模型客户技术岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '把工程能力前移到客户现场，可以缩短需求误解到产品改进的反馈回路，并处理标准产品无法预先覆盖的集成差异。',
      businessValue: '更快跨过 POC 到生产的“最后一公里”，同时把可复用需求带回产品，降低后续类似客户交付成本。',
      boundary: '高投入现场模式不适合所有客户；若缺少产品化纪律，FDE 也可能退化为不可复制的定制开发。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '两类岗位不是完全同义，本条只归纳“客户现场技术价值实现”这一共同结果。',
  }),
  defineCandidate({
    id: 'ST-021', slug: 'technical-deployment-lead-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'Technical Deployment Lead 负责把试点变成可运营部署',
    summary: 'Anthropic 列出 Technical Deployment Lead；阿里云招聘中出现 Agent 交付和 MaaS 算力资源交付岗位。两地岗位都把上线后的运营责任从临时项目中单独拉出。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['Technical Deployment Lead', 'Agent 交付', '运营'], toolIds: ['role-gap-analysis', 'poc-success-canvas'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '从 POC 到生产需要持续协调技术、风险、业务使用、容量和交接，不能靠一次项目经理推动。',
    salesImplication: '签约前应明确部署负责人、客户侧配合、运营指标、知识交接和退出路径。',
    roleOrgImplication: '该角色连接交付、客户成功和技术实施，核心结果是可持续运行而非按时完成里程碑。',
    nextAction: '为一个虚构项目写出部署负责人在启动、试点、扩展和运营四阶段必须交付的证据。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — Technical Deployment Lead', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — Agent 交付与 MaaS 交付相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出美国和英国的 Technical Deployment Lead 岗位。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可检索到 Agent 交付和 MaaS 算力资源交付与项目管理岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '专门部署负责人把试点知识、生产约束和运营责任串成连续链条，减少销售结束后信息断裂。',
      businessValue: '可缩短上线时间、减少重复发现，并提高客户从首次成功到稳定使用的转化率。',
      boundary: '岗位名称不等于成熟流程；若客户没有业务责任人和运营预算，供应商部署负责人也无法单方面完成采用。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位名称与检索结果为当日观察；不声称中外岗位职责完全一致。',
  }),
  defineCandidate({
    id: 'ST-022', slug: 'presales-program-lead-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'Pre-Sales Program Lead 把单次售前经验变成规模化机制',
    summary: 'Anthropic 在 FDE 体系中招聘 Pre-Sales Program Lead；阿里云也持续招聘售前解决方案架构与商业技术岗位。复杂 AI 售前需要方法、资产和反馈闭环，而不只依赖个人英雄。',
    kind: 'role', domains: ['role_org', 'enterprise_sales', 'ai_technology'], topicSlugs: ['ai-commercial-role-map'],
    tags: ['Pre-Sales Program Lead', '售前机制', '规模化'], toolIds: ['company-role-research', 'transition-evidence'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '客户共创增多后，案例、评测、资格判断和交接若不能复用，售前成本会随项目线性增长。',
    salesImplication: '有复杂项目经验的人应展示自己建立的模板、门槛、复盘和跨团队机制，而不只展示成交额。',
    roleOrgImplication: '售前项目运营成为商务、FDE、产品和交付之间的组织接口。',
    nextAction: '把一次复杂售前经历改写成“建立了什么可复用机制、被谁采用、如何改进”。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — Pre-Sales Program Lead, Forward Deployed Engineering', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — 售前解决方案架构与商业技术相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出 Pre-Sales Program Lead, Forward Deployed Engineering 岗位。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可见售前解决方案架构与大量商业技术相关岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '专门角色把分散在个人经验中的资格判断、方案资产和复盘规则编码为团队可复用系统。',
      businessValue: '提高售前吞吐与一致性，减少重复方案劳动，并使产品更快吸收一线共性需求。',
      boundary: '过度标准化会压低复杂客户的适配度；机制必须允许例外并以赢率、周期和交付质量持续校正。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '两方岗位事实支持售前体系化需求，但岗位数量和组织成熟度不作行业统计推断。',
  }),
  defineCandidate({
    id: 'ST-023', slug: 'ai-fluency-education-lead-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'AI Fluency Education Lead 把采用能力变成专门岗位',
    summary: 'Anthropic 招聘 AI Fluency Education Lead；阿里云招聘中也可见 AI 培训销售相关岗位。AI 素养开始同时服务于内部采用、客户教育和商业转化。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['AI Fluency', '客户教育', '采用'], toolIds: ['role-gap-analysis', 'transition-evidence'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '组织采用不只是购买许可，还要让不同角色学会判断何时使用、如何复核以及何时停止。',
    salesImplication: '培训方案要连接真实工作与采用指标，不能把听课人数当成业务改变。',
    roleOrgImplication: '内容、教育、技术、销售和组织变革能力开始在 AI Fluency 岗位交汇。',
    nextAction: '设计一个 30 分钟销售场景练习，要求参与者完成任务、判断风险并解释人工复核点。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — AI Fluency Education Lead', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — AI 培训销售专家相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出 AI Fluency Education Lead，并同时存在教育内容、课程和工程相关岗位。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可检索到 AI 培训销售专家岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '专门教育角色把产品知识转化为分角色任务、判断规则和反馈数据，填补购买与持续使用之间的断层。',
      businessValue: '可提升采用速度、减少误用，并让客户教育成为发现新场景和扩展机会的渠道。',
      boundary: '一次课程不能证明行为改变；必须观察真实任务表现、复核质量和持续使用，且培训内容需随产品更新。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '两地岗位的服务对象不同，本条只归纳 AI 教育与采用成为专门工作这一共同方向。',
  }),
  defineCandidate({
    id: 'ST-024', slug: 'agentops-gtm-systems-role', seedCategory: 'ai_role_change', conclusionScope: 'cross_organization',
    title: 'AgentOps 正在进入 GTM 与商业系统岗位',
    summary: 'Anthropic 招聘 DevOps / AgentOps Engineer, GTM Systems；阿里云招聘中出现 Agent 沙箱管控相关技术岗位。商业自动化开始需要可靠性、权限和运行治理。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'agent-business-model'],
    tags: ['AgentOps', 'GTM Systems', '商业运营'], toolIds: ['company-role-research', 'role-gap-analysis'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '当 Agent 操作 CRM、内容和客户流程时，故障、权限和数据质量会直接影响收入系统。',
    salesImplication: '销售运营经验仍有价值，但需要补足 Agent 可观测、权限、评测和人工接管。',
    roleOrgImplication: 'GTM Systems 可能成为销售运营、工程、安全和 AgentOps 的共同责任面。',
    nextAction: '为一个销售 Agent 列出触发、权限、日志、质量阈值、失败和人工接管六项运行要求。',
    evidence: [
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — DevOps / AgentOps Engineer, GTM Systems', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — Agent 沙箱管控相关岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Anthropic 招聘页在核验日列出 DevOps / AgentOps Engineer, GTM Systems 及 GTM Systems 项目岗位。', evidenceIndexes: [1] },
      { statement: '阿里云招聘页在核验日可检索到 Agent 沙箱管控相关技术岗位。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: 'Agent 进入商业系统后，自动化从一次脚本变成持续运行服务，必须有人管理版本、权限、质量和事故。',
      businessValue: '专门运维可降低错误触达、数据污染和流程中断，保护收入流程并提高自动化资产复用率。',
      boundary: '岗位是否独立取决于规模；小团队可由平台或销售运营兼任，但责任和指标仍需明确。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '跨公司岗位共同支持运行治理需求；不把两个岗位样本外推为统一职业标准。',
  }),
  defineCandidate({
    id: 'ST-025', slug: 'eu-ai-act-august-2026', seedCategory: 'org_adoption', conclusionScope: 'editorial_synthesis',
    title: '欧盟 AI Act 于 2026 年 8 月进入更完整适用阶段',
    summary: '欧盟委员会公布 2026 年 8 月 2 日的适用时间线，同时保留部分高风险系统的后续过渡安排；NIST AI RMF 则提供自愿风险治理结构。面向欧洲的销售要把法律角色和运营控制分开确认。',
    kind: 'update', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-trust-governance', 'ai-buying-committee'],
    tags: ['EU AI Act', '透明度', '治理'], toolIds: ['stakeholder-adoption-risk', 'ai-maturity-scan'],
    publishedAt: '2026-08-03T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '同一 AI 场景中，提供者、部署者、用途和地域会改变义务；通用“已合规”承诺可能误导客户。',
    salesImplication: '先识别客户法律角色、用途和时间线，再由法律团队确认适用义务，不把风险框架等同于法律结论。',
    roleOrgImplication: '产品、法务、安全、内容和业务运营要共同维护透明度、监督和记录流程。',
    nextAction: '为一个虚构欧洲场景写出提供者、部署者、用途、风险类别和五个待法律确认问题。',
    evidence: [
      { sourceId: 'eu-ai-act', title: 'AI Act', publisher: 'European Commission', url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai', publishedAt: '2026-08-03T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
      { sourceId: 'nist-ai-rmf', title: 'AI Risk Management Framework', publisher: 'NIST', url: 'https://www.nist.gov/itl/ai-risk-management-framework', publishedAt: '2023-01-26T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: '欧盟委员会页面列出 AI Act 于 2026 年 8 月 2 日进入适用阶段，并说明部分高风险规则另有过渡时间。', evidenceIndexes: [1] },
      { statement: 'NIST AI RMF 提供 Govern、Map、Measure、Manage 的自愿风险管理结构，可用于组织运营准备。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '法律时间线触发客户重新检查角色、用途和证据，风险框架则帮助把义务转成可运营控制，但二者权威性质不同。',
      businessValue: '提前区分法律确认与工程控制，可以减少错误承诺、缩短客户尽调，并形成更可信的欧洲市场进入计划。',
      boundary: 'NIST 框架不能证明 EU AI Act 合规，本内容也不是法律意见；具体适用性必须由合格法律人员判断。',
    },
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'official_fact',
    verificationNotes: '法律时间线仅以欧盟委员会为权威来源，第二事实用于解释组织落地而非交叉证明法律结论；发布前必须法律复核。',
  }),
  defineCandidate({
    id: 'ST-026', slug: 'organizational-readiness-evidence', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: '组织准备度要由工作流、责任与反馈闭环共同证明',
    summary: 'OpenAI 的 Univé 案例把领导力、治理和员工创新结合；Google 的企业 Agent 平台把身份、模拟和可观测纳入生命周期。积极的组织准备度不是少数人会用 AI，而是组织能持续选择、运行和改进工作。',
    kind: 'explainer', domains: ['role_org', 'enterprise_sales', 'ai_technology'], topicSlugs: ['workflow-adoption', 'ai-trust-governance'],
    tags: ['组织准备度', '反馈闭环', '工作流'], toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'],
    publishedAt: '2026-07-31T00:00:00.000Z', freshness: 'current',
    whyItMatters: '个人能力是必要条件，但只有工作流、责任和反馈闭环同时存在，使用才能转化为可持续组织产能。',
    salesImplication: '采用方案应积极建设三个证据：目标工作流已重构、责任人能处理异常、真实使用反馈能进入下一轮改进。',
    roleOrgImplication: '领导设方向和资源，经理重构工作，员工提供一线反馈，平台与风险团队守住运行边界。',
    nextAction: '用成熟度扫描分别记录工作流、责任和反馈闭环的现有证据，并为最弱一项安排 30 天实验。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Univé builds an AI-ready workforce', publisher: 'OpenAI', url: 'https://openai.com/index/unive', publishedAt: '2026-07-31T00:00:00.000Z', level: 'official' },
      { sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 客户案例把 Univé 的 AI 人才建设描述为领导支持、治理和员工主导创新的组合。', evidenceIndexes: [1] },
      { statement: 'Google Gemini Enterprise 官方材料把身份、模拟、可观测与生命周期治理纳入企业 Agent 平台。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '工作流规定 AI 在哪里创造价值，责任体系处理例外，反馈闭环把真实失败重新输入产品和培训，三者形成持续改进系统。',
      businessValue: '组织可以把零散试用转化为稳定产能，并随着使用证据扩大范围，而不是反复启动互不相连的试点。',
      boundary: '三项证据的强度应与风险匹配；不能因流程齐全就忽略用户判断，也不能把单一厂商案例当作普遍因果。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '已按终审意见改为正面倡导的组织准备度模型；案例效果保持企业自述属性。',
  }),
  defineCandidate({
    id: 'ST-027', slug: 'agent-lifecycle-needs-owner', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: '每个生产 Agent 都需要完整生命周期责任人',
    summary: 'Google 企业 Agent 平台强调身份、网关、模拟和可观测；阿里云 Agent Identity 管理身份、凭据与权限。规模化之后，创建、变更、暂停和下线必须有人负责。',
    kind: 'method', domains: ['role_org', 'ai_technology'], topicSlugs: ['ai-trust-governance', 'workflow-adoption'],
    tags: ['Agent 生命周期', '责任人', '控制面'], toolIds: ['stakeholder-adoption-risk', 'ai-maturity-scan'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '无人负责的 Agent 会积累过期知识、长期凭据和隐性业务依赖，出错时也找不到暂停决策者。',
    salesImplication: '方案应明确谁批准上线、谁看日志、谁更新提示词和工具、谁能暂停、谁确认下线。',
    roleOrgImplication: 'Agent 应像员工账号和企业应用一样有所有者、版本、权限审查和退出流程。',
    nextAction: '为一个 Agent 指定业务、技术、安全和下线四类责任人，并写出季度复核日期。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' },
      { sourceId: 'aliyun-model-studio', title: 'Agent Identity 产品文档', publisher: '阿里云', url: 'https://help.aliyun.com/zh/agentidentity/', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'Google 官方材料把 Agent 身份、网关、模拟、可观测和生命周期管理放入统一平台。', evidenceIndexes: [1] },
      { statement: '阿里云 Agent Identity 官方文档提供 Agent 身份、凭据和第三方访问权限管理。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '生命周期责任把创建时的一次授权转化为持续复核，确保业务变化、人员离职或风险事件能触发变更与撤销。',
      businessValue: '降低过度权限和遗留 Agent 的事故面，缩短故障处置时间，也让平台可以安全复用更多连接。',
      boundary: '工具只能记录和执行控制，无法替企业决定业务风险接受人；低风险实验也应至少有明确所有者和到期日。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '两个独立平台事实共同支持生命周期能力需求；责任模型是编辑建议，需按客户组织落地。',
  }),
  defineCandidate({
    id: 'ST-028', slug: 'architecture-contract-as-org-memory', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: '把组织标准编码成 Agent 可执行的任务契约',
    summary: 'Google Cloud 建议以可验证子任务和最小权限组织委派；Anthropic 建议用简单可组合模式与检查点。把标准写进任务契约，可以让组织经验从口头要求变成可测试边界。',
    kind: 'method', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['workflow-adoption', 'ai-poc-scale'],
    tags: ['任务契约', '组织记忆', '验收'], toolIds: ['ai-maturity-scan', 'poc-success-canvas'],
    publishedAt: '2026-08-21T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '标准只存在于专家脑中时，不同团队和 Agent 会重复产生不一致结果，专家也持续承担低价值复核。',
    salesImplication: '价值主张可以从“生成更快”升级为“把标准复用到更多任务并减少重复评审”。',
    roleOrgImplication: '专家从逐项执行转向维护标准、审核例外和改进契约，业务仍保留最终判断权。',
    nextAction: '选一个重复流程，写出输入、输出、三条硬规则、一个人工例外门和失败升级人。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: 'How agents can delegate better', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/how-agents-can-delegate-better', publishedAt: '2026-08-21T00:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-news', title: 'Building effective agents', publisher: 'Anthropic', url: 'https://www.anthropic.com/engineering/building-effective-agents', publishedAt: '2024-12-19T00:00:00.000Z', level: 'official' },
    ],
    supportingFacts: [
      { statement: 'Google Cloud 建议 Agent 委派采用可可靠验证的子任务、最小数据权限和必要的人类判断点。', evidenceIndexes: [1] },
      { statement: 'Anthropic 建议从简单可组合模式开始，并在 Prompt chaining 等 Workflow 中设置程序化检查门。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '任务契约把专家标准转成输入输出、规则和验收门，使系统可以自动检查常规情况并显式升级例外。',
      businessValue: '减少重复评审、提高跨团队一致性，并让专家时间转向高价值例外和标准改进。',
      boundary: '隐性知识未被充分表达时，契约会产生虚假确定性；需要持续用失败案例更新，不能阻止合理例外。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '已移除单一 AWS 案例依赖，改由两家不同厂商的工程方法支持组织契约判断。',
  }),
  defineCandidate({
    id: 'ST-029', slug: 'enterprise-ai-from-assistance-to-execution', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: '企业 AI 采用焦点正在从辅助转向受控执行',
    originalTitle: 'From assistance to execution: How enterprises put AI to work',
    summary: 'OpenAI 企业材料描述从辅助走向执行；腾讯云 ADP 同时提供 Workflow、Multi-Agent、知识和平台管理。能力组合正在支持流程执行，但治理和运营必须同步升级。',
    kind: 'update', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['workflow-adoption', 'agent-business-model'],
    tags: ['企业采用', '受控执行', '运营'], toolIds: ['ai-maturity-scan', 'value-hypothesis-one-pager'],
    publishedAt: '2026-08-12T06:00:00.000Z', freshness: 'current',
    whyItMatters: '从回答问题到执行流程会增加工具权限、外部影响、失败恢复和业务责任，不能沿用个人助手的治理方式。',
    salesImplication: '机会判断要区分辅助、协作和执行三层，并为每次升级写出新增价值与新增控制。',
    roleOrgImplication: '组织需要从工具培训转向工作设计、AgentOps、责任治理和持续反馈。',
    nextAction: '把一个场景标为辅助、协作或执行，并写出升级到下一层所需的权限、评测和责任证据。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'From assistance to execution: How enterprises put AI to work', publisher: 'OpenAI', url: 'https://openai.com/index/how-enterprises-put-ai-to-work', publishedAt: '2026-08-12T06:00:00.000Z', level: 'official' },
      { sourceId: 'tencent-cloud-ai', title: '腾讯云智能体开发平台 ADP', publisher: '腾讯云', url: 'https://cloud.tencent.com/document/product/1759', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 企业采用材料把趋势描述为从个人辅助扩展到更复杂的工作执行。', evidenceIndexes: [1] },
      { statement: '腾讯云 ADP 官方文档提供 Workflow、Multi-Agent、知识、工具和平台管理能力。', evidenceIndexes: [2] },
    ],
    deeperAnalysis: {
      mechanism: '执行型系统把模型输出变成对工具和业务状态的动作，价值更直接，同时错误也从内容问题升级为流程后果。',
      businessValue: '受控执行可减少人工交接与等待，把 AI 价值从个人节时扩大到周期、吞吐和服务水平。',
      boundary: '并非所有辅助场景都应升级执行；高损失、低可逆或缺少客观验收的动作必须保留人类批准。',
    },
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '国际采用叙事与大陆产品能力共同支持方向，但均不能证明所有企业已完成执行型转型。',
  }),
  defineCandidate({
    id: 'ST-030', slug: 'skills-change-ai-work', seedCategory: 'org_adoption', conclusionScope: 'cross_organization',
    title: 'AI 转型首先表现为岗位结果与技能组合重组',
    summary: 'OpenAI 工作研究强调 AI 扩展可完成的任务；Anthropic 与阿里云的岗位组合同时出现 Applied AI、FDE、AgentOps、解决方案与交付角色。岗位名称之外，结果责任正在重新组合。',
    kind: 'explainer', domains: ['role_org', 'enterprise_sales', 'ai_technology'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['技能重组', '岗位结果', '转岗'], toolIds: ['transition-evidence', 'role-gap-analysis'],
    publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '岗位名称可能保持不变，但需求发现、技术判断、评测、交付和采用的组合已经变化。',
    salesImplication: '转岗准备应围绕目标岗位交付结果和真实作品证据，而不是堆叠通用 AI 课程证书。',
    roleOrgImplication: '组织要按工作结果重画角色接口，明确哪些旧能力保留、哪些被工具增强、哪些成为新责任。',
    nextAction: '选择一个目标岗位，把结果分为保留、重组、新增三类，并为每类找到中外岗位原页证据。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'How AI is expanding what people do at work', publisher: 'OpenAI', url: 'https://openai.com/index/how-ai-is-expanding-what-people-do-at-work', publishedAt: '2026-07-27T00:00:00.000Z', level: 'official' },
      { sourceId: 'anthropic-careers', title: 'Anthropic Careers — Applied AI, FDE and AgentOps roles', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' },
      { sourceId: 'aliyun-careers', title: '阿里云招聘 — AI 解决方案、商业技术与 Agent 交付岗位', publisher: '阿里云', url: 'https://careers.aliyun.com/off-campus/position-list?lang=zh', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', language: 'zh', dateBasis: 'observed' },
    ],
    supportingFacts: [
      { statement: 'OpenAI 发布的工作研究把 AI 使用描述为扩展人们可完成的任务和工作范围。', evidenceIndexes: [1] },
      { statement: 'Anthropic 与阿里云招聘页在核验日同时呈现 Applied AI、FDE、AgentOps、AI 解决方案、商业技术和 Agent 交付等角色组合。', evidenceIndexes: [2, 3] },
    ],
    deeperAnalysis: {
      mechanism: '技术把部分执行压缩后，岗位价值向问题定义、系统判断、跨团队落地和持续运营迁移，原有能力被重新组合而非整体消失。',
      businessValue: '个人可更精准地准备转岗证据，组织也能围绕真实结果补岗和培训，减少“课程很多、能力无法落地”。',
      boundary: '招聘页只是需求快照，不等于全部劳动力市场；岗位变化速度、行业和公司阶段差异很大，需要持续复核。',
    },
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '用工作研究和中外招聘快照替换单一平台预测；不声称岗位变化已形成统一行业标准。',
  }),
] as const satisfies readonly SeedCandidate[];
