import type { KnowledgeTool, LocalizedText } from '../domain';

const zh = (value: string): LocalizedText => ({ zh: value });

export const knowledgeTools = [
  {
    id: 'company-role-research',
    title: zh('AI 公司与目标岗位研究画布'),
    scenario: zh('在投递或约谈前，把公司战略、产品、客户、岗位和证据放在同一页判断。'),
    estimatedMinutes: 25,
    outputFormat: 'markdown',
    inputPrompts: [
      zh('这家公司解决什么业务问题，主要客户与付费路径是什么？'),
      zh('目标岗位要负责哪些结果，而不只是哪些任务？'),
      zh('哪些结论来自公司自述，哪些有独立证据，哪些仍是假设？'),
    ],
    templateMarkdown: '# AI 公司与目标岗位研究\n\n## 公司与产品事实\n\n## 目标客户与价值路径\n\n## 岗位结果\n\n## 已有证据与待验证假设\n',
    exampleMarkdown: '# AI 公司与目标岗位研究（虚构示例）\n\n## 公司与产品事实\n星河智能提供企业知识检索产品。\n\n## 目标客户与价值路径\n目标客户是需要降低内部检索时间的服务型企业。\n\n## 岗位结果\n推动试点从验证检索准确率走向业务部门采用。\n\n## 已有证据与待验证假设\n事实：官网列出企业版；假设：采购由 IT 与业务共同决策。\n',
    completionCriteria: [zh('至少列出三个可回溯事实'), zh('区分事实、企业自述与个人假设'), zh('写出一个面试或沟通中的验证问题')],
    safetyNote: zh('只使用公开信息和虚构示例，不填写真实客户敏感数据。'),
  },
  {
    id: 'transition-evidence',
    title: zh('30 天转岗能力证据清单'),
    scenario: zh('把传统 To B 销售经验翻译成 AI 商业岗位能识别的能力证据。'),
    estimatedMinutes: 20,
    outputFormat: 'markdown',
    inputPrompts: [zh('我推动过什么复杂决策？'), zh('我怎样验证业务价值和采用条件？'), zh('还缺哪一项 AI 技术或组织转型证据？')],
    templateMarkdown: '# 30 天转岗能力证据\n\n## 已有复杂销售证据\n\n## 可迁移到 AI 岗位的能力\n\n## 30 天补证动作\n\n## 面试表达\n',
    exampleMarkdown: '# 30 天转岗能力证据（虚构示例）\n\n## 已有复杂销售证据\n协调业务、IT、采购完成三轮方案评审。\n\n## 可迁移到 AI 岗位的能力\n把技术限制翻译为可验收的业务指标。\n\n## 30 天补证动作\n完成一份虚构 AI POC 成功标准。\n\n## 面试表达\n我擅长把多方关注点转成共同验收条件。\n',
    completionCriteria: [zh('至少三条已有证据'), zh('每条证据对应一个目标岗位结果'), zh('列出可在 30 天内完成的补证动作')],
    safetyNote: zh('对真实项目去标识化，不写客户名称、联系人或保密数字。'),
  },
  {
    id: 'role-gap-analysis',
    title: zh('岗位描述与个人能力差距分析'),
    scenario: zh('比较目标岗位原文与个人证据，确定投递前最值得补齐的差距。'),
    estimatedMinutes: 20,
    outputFormat: 'markdown',
    inputPrompts: [zh('岗位明确要求哪些结果与协作对象？'), zh('我能为每项要求提供什么证据？'), zh('哪些差距可以用学习、作品或访谈补齐？')],
    templateMarkdown: '# 岗位能力差距分析\n\n| 岗位结果 | 我的证据 | 证据强度 | 补齐动作 |\n|---|---|---|---|\n',
    exampleMarkdown: '# 岗位能力差距分析（虚构示例）\n\n| 岗位结果 | 我的证据 | 证据强度 | 补齐动作 |\n|---|---|---|---|\n| 设计企业 AI 试点 | 曾设计数据平台试点 | 中 | 写一份 AI POC 成功标准 |\n',
    completionCriteria: [zh('覆盖岗位前三项结果'), zh('证据强度有明确理由'), zh('每个关键差距都有下一步与截止时间')],
    safetyNote: zh('保留岗位原文链接；不要虚构尚未具备的经历。'),
  },
  {
    id: 'discovery-interview',
    title: zh('大客户发现访谈提纲'),
    scenario: zh('在 AI 项目立项或试点前，发现业务目标、现有流程、数据、风险与决策链。'),
    estimatedMinutes: 15,
    outputFormat: 'markdown',
    inputPrompts: [zh('哪个业务结果需要改变，现状基线是什么？'), zh('流程中谁执行、谁审核、谁承担风险？'), zh('什么证据会让决策者继续或停止？')],
    templateMarkdown: '# 大客户发现访谈\n\n## 业务结果与基线\n\n## 当前流程与阻力\n\n## 数据、系统与安全\n\n## 决策人和验收人\n\n## 下一次验证\n',
    exampleMarkdown: '# 大客户发现访谈（虚构示例）\n\n## 业务结果与基线\n将方案检索平均用时从 40 分钟降到 15 分钟。\n\n## 当前流程与阻力\n资料分散，法务要求保留引用来源。\n\n## 决策人和验收人\n业务负责人确认价值，IT 与安全确认边界。\n\n## 下一次验证\n抽取 30 个脱敏问题测试答案与引用。\n',
    completionCriteria: [zh('至少一个有基线的业务结果'), zh('覆盖业务、IT、安全与最终使用者'), zh('形成一个可验证的下一步')],
    safetyNote: zh('页面只做提纲；不要把真实访谈记录或客户数据保存在本站。'),
  },
  {
    id: 'ai-maturity-scan',
    title: zh('客户 AI 成熟度快速扫描'),
    scenario: zh('判断客户当前更适合概念验证、受控试点还是规模化采用。'),
    estimatedMinutes: 15,
    outputFormat: 'markdown',
    inputPrompts: [zh('业务问题和负责人是否明确？'), zh('数据、身份、权限与评估是否可用？'), zh('组织是否有使用规范、培训与变更负责人？')],
    templateMarkdown: '# 客户 AI 成熟度扫描\n\n## 业务与负责人\n\n## 数据与技术\n\n## 风险与治理\n\n## 采用与运营\n\n## 建议阶段\n',
    exampleMarkdown: '# 客户 AI 成熟度扫描（虚构示例）\n\n## 业务与负责人\n客服总监负责，目标是缩短新人查找答案时间。\n\n## 数据与技术\n知识库可用，但权限继承尚未验证。\n\n## 风险与治理\n需要安全评审和人工抽检。\n\n## 建议阶段\n先做脱敏、只读、可撤回的受控试点。\n',
    completionCriteria: [zh('四个维度都有证据而非主观打分'), zh('指出最大阻塞和负责人'), zh('建议阶段与证据相匹配')],
    safetyNote: zh('只记录去标识化判断，不保存客户系统、账号或数据详情。'),
  },
  {
    id: 'value-hypothesis-one-pager',
    title: zh('AI 价值假设一页纸'),
    scenario: zh('把技术能力翻译成可测量的业务变化、成本与不成立条件。'),
    estimatedMinutes: 20,
    outputFormat: 'markdown',
    inputPrompts: [zh('谁的哪一步工作会改变？'), zh('业务结果用什么基线和指标衡量？'), zh('哪些风险、成本或前提会让假设不成立？')],
    templateMarkdown: '# AI 价值假设一页纸\n\n## 用户与工作\n\n## 当前基线\n\n## 价值假设\n\n## 证据与成本\n\n## 不成立条件\n\n## 下一步实验\n',
    exampleMarkdown: '# AI 价值假设一页纸（虚构示例）\n\n## 用户与工作\n售前每周整理相似案例。\n\n## 当前基线\n每次平均 90 分钟，引用错误需返工。\n\n## 价值假设\n若检索助手提供可追溯引用，准备时间可降低且返工不增加。\n\n## 不成立条件\n引用准确率未达到人工验收线。\n\n## 下一步实验\n用 20 个历史问题做盲测。\n',
    completionCriteria: [zh('有具体用户、工作和基线'), zh('价值指标与风险指标同时存在'), zh('写明假设不成立和停止条件')],
    safetyNote: zh('示例必须虚构；真实商业数字请在用户自有安全文档中处理。'),
  },
  {
    id: 'poc-success-canvas',
    title: zh('概念验证成功标准画布'),
    scenario: zh('在 POC 开始前统一业务、技术、风险、采用和退出标准。'),
    estimatedMinutes: 25,
    outputFormat: 'markdown',
    inputPrompts: [zh('业务、技术和风险指标分别是什么？'), zh('谁验收，每项证据从哪里来？'), zh('何时扩展、修正或停止试点？')],
    templateMarkdown: '# POC 成功标准\n\n## 范围与假设\n\n## 业务指标\n\n## 技术指标\n\n## 风险与治理指标\n\n## 使用与采用指标\n\n## 扩展和停止门\n',
    exampleMarkdown: '# POC 成功标准（虚构示例）\n\n## 范围与假设\n只读检索 500 份脱敏文档。\n\n## 业务指标\n完成任务时间下降且返工率不增加。\n\n## 技术指标\n答案必须附原文引用。\n\n## 风险与治理指标\n越权访问为零，全部操作可审计。\n\n## 扩展和停止门\n连续两轮达到验收线才扩展；出现越权立即停止。\n',
    completionCriteria: [zh('至少覆盖业务、技术、风险和采用四类指标'), zh('每项有负责人和取证方式'), zh('扩展与停止条件可执行')],
    safetyNote: zh('本工具不替代客户的安全、法律或采购审批。'),
  },
  {
    id: 'stakeholder-adoption-risk',
    title: zh('干系人与组织采用风险清单'),
    scenario: zh('识别 AI 项目从试用到规模化时的决策人、受影响者、风险与沟通动作。'),
    estimatedMinutes: 20,
    outputFormat: 'markdown',
    inputPrompts: [zh('谁拥有业务结果、预算、技术和风险决定权？'), zh('谁的工作方式会改变，可能获得或失去什么？'), zh('每类风险需要什么证据、承诺和升级路径？')],
    templateMarkdown: '# 干系人与采用风险\n\n| 角色 | 关注结果 | 担忧或风险 | 所需证据 | 下一步 |\n|---|---|---|---|---|\n',
    exampleMarkdown: '# 干系人与采用风险（虚构示例）\n\n| 角色 | 关注结果 | 担忧或风险 | 所需证据 | 下一步 |\n|---|---|---|---|---|\n| 业务负责人 | 缩短处理时间 | 团队不使用 | 试点使用记录 | 共同定义场景 |\n| 安全负责人 | 数据不越权 | 权限继承错误 | 权限测试与审计 | 安排威胁建模 |\n',
    completionCriteria: [zh('覆盖业务、IT、安全、采购和最终使用者'), zh('每个关键风险都有证据或验证动作'), zh('明确升级、暂停和撤回责任')],
    safetyNote: zh('使用角色称谓和虚构示例，不保存真实姓名或敏感关系信息。'),
  },
] as const satisfies readonly KnowledgeTool[];
