import type { KnowledgeTopic, LocalizedText } from '../domain';

const zh = (value: string): LocalizedText => ({ zh: value });

export const knowledgeTopics = [
  {
    slug: 'ai-poc-scale',
    title: zh('从 AI POC 到规模化采用'),
    summary: zh('把演示效果转换成业务、技术、风险和组织采用都能验收的扩展条件。'),
    domains: ['ai_technology', 'enterprise_sales', 'role_org'],
    itemIds: ['ST-005', 'ST-009', 'ST-010', 'ST-011', 'ST-012', 'ST-015', 'ST-020', 'ST-028'],
    problemDefinition: zh('很多 AI 项目能完成一次演示，却没有共同的成功标准、生产控制和后续采用责任，因此无法安全扩展。'),
    keyChanges: zh('判断重点正从模型能力转向端到端任务结果、确定性控制、持续评估、组织责任和可回退运营。'),
    salesJudgment: zh('销售应在 POC 前确认四类验收门、负责人和停止条件，并把“能做”与“值得扩展”分开。'),
    roleOrgImpact: zh('前线工程、部署负责人、业务所有者和治理角色需要共同维护从试点到生产的证据链。'),
    toolIds: ['ai-maturity-scan', 'poc-success-canvas'],
  },
  {
    slug: 'ai-buying-committee',
    title: zh('AI 大客户购买委员会与信任门'),
    summary: zh('识别业务、IT、安全、法务、采购与最终使用者在 AI 决策中的不同证据要求。'),
    domains: ['enterprise_sales', 'ai_technology', 'role_org'],
    itemIds: ['ST-003', 'ST-011', 'ST-013', 'ST-018', 'ST-025'],
    problemDefinition: zh('AI 项目的价值、数据、责任和合规风险分散在多个角色，单靠业务关系或产品演示无法形成组织承诺。'),
    keyChanges: zh('购买决策增加了数据保留、权限、透明度、人工监督、使用采用和撤回机制等信任证据。'),
    salesJudgment: zh('发现阶段要逐一确认谁拥有业务结果、谁有否决权、每个门需要什么证据，以及冲突如何升级。'),
    roleOrgImpact: zh('复杂销售人员需要成为多方证据协调者，而不是只管理单一关键人的关系。'),
    toolIds: ['discovery-interview', 'stakeholder-adoption-risk'],
  },
  {
    slug: 'agent-business-model',
    title: zh('Agent 商业模式与价值证据'),
    summary: zh('从模型单价、Agent 能力、运营成本和业务结果四层判断 Agent 是否具备可持续商业价值。'),
    domains: ['ai_technology', 'enterprise_sales', 'role_org'],
    itemIds: ['ST-001', 'ST-002', 'ST-004', 'ST-006', 'ST-007', 'ST-014', 'ST-017', 'ST-024', 'ST-029'],
    problemDefinition: zh('Agent 容易把能力演示、速度承诺或厂商案例误当成客户自己的经济价值与生产可用性。'),
    keyChanges: zh('成本核算需要包含完成率、复核、重试、容量、身份、观测和运营，而价值必须由客户基线与实验验证。'),
    salesJudgment: zh('机会推进应明确价值假设、不成立条件、可变成本和生产责任，不用模型指标替代业务证据。'),
    roleOrgImpact: zh('GTM、解决方案和 AgentOps 岗位将共同承担从价值设计到生产运营的闭环。'),
    toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'],
  },
  {
    slug: 'ai-commercial-role-map',
    title: zh('AI 商业岗位地图与转岗路径'),
    summary: zh('用真实岗位结果理解 AI Architect、FDE、部署、售前项目、教育和 AgentOps 等新型分工。'),
    domains: ['role_org', 'enterprise_sales', 'ai_technology'],
    itemIds: ['ST-019', 'ST-020', 'ST-021', 'ST-022', 'ST-023', 'ST-024', 'ST-030'],
    problemDefinition: zh('传统 To B 销售常按岗位名称判断机会，却不清楚 AI 商业岗位实际负责的结果、协作边界和技术证据。'),
    keyChanges: zh('岗位正在围绕客户共创、快速部署、规模运营、采用教育和 Agent 治理重新组合，而非简单更换名称。'),
    salesJudgment: zh('转岗者应把过往复杂销售经历映射到目标岗位结果，并对缺口安排可验证的补证动作。'),
    roleOrgImpact: zh('个人需要持续更新技能组合，组织也要明确前线交付、平台治理和采用运营之间的责任。'),
    toolIds: ['company-role-research', 'transition-evidence', 'role-gap-analysis'],
  },
  {
    slug: 'workflow-adoption',
    title: zh('工作流重构与组织采用'),
    summary: zh('把 AI 从个人辅助工具转成有负责人、控制、学习机制和采用证据的工作方式。'),
    domains: ['role_org', 'enterprise_sales', 'ai_technology'],
    itemIds: ['ST-005', 'ST-014', 'ST-016', 'ST-021', 'ST-023', 'ST-026', 'ST-027', 'ST-028', 'ST-029', 'ST-030'],
    problemDefinition: zh('购买工具或完成培训并不自动改变工作结果；流程、激励、经理支持、责任和反馈机制缺一不可。'),
    keyChanges: zh('领先实践把采用对象从“会不会用工具”扩展到任务分工、人工判断、运营节奏和组织学习。'),
    salesJudgment: zh('发现问题时要区分个人辅助、团队协作和流程执行，并验证客户是否具备进入下一层的条件。'),
    roleOrgImpact: zh('经理、教育负责人、部署负责人和一线使用者需要共同设计新流程并持续修正。'),
    toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'],
  },
  {
    slug: 'ai-trust-governance',
    title: zh('AI 信任、治理与可回退运营'),
    summary: zh('把安全、合规、证据、人工监督和撤回能力变成销售与交付共同维护的产品条件。'),
    domains: ['ai_technology', 'enterprise_sales', 'role_org'],
    itemIds: ['ST-003', 'ST-004', 'ST-006', 'ST-008', 'ST-009', 'ST-010', 'ST-013', 'ST-015', 'ST-018', 'ST-025', 'ST-027'],
    problemDefinition: zh('治理若只在上线前做一次审批，就难以应对模型、数据、工作流和法规持续变化带来的风险。'),
    keyChanges: zh('治理正在转向全生命周期的身份、权限、评估、审计、透明度、人工门和快速回退。'),
    salesJudgment: zh('销售不能承诺超出证据的安全或合规结论，应把风险问题转成可验证条件并交给相应负责人决策。'),
    roleOrgImpact: zh('业务、技术和风险角色需要共享审计事实，但仍保留各自不可替代的最终责任。'),
    toolIds: ['stakeholder-adoption-risk', 'poc-success-canvas'],
  },
] as const satisfies readonly KnowledgeTopic[];
